In [1]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page

In [2]:
# import sys
# sys.path.append("VAX GG")

In [15]:
import numpy as np
import pandas as pd
from datetime import date

In [4]:
#with open('Vax - Vacuums & Cleaners - The Good Guys.html', 'r') as f:
with open('Dyson.html', 'r') as f:
    html_string = f.read()
html_string

'<!doctype HTML>\n\n\n<html xmlns:wairole="http://www.w3.org/2005/01/wai-rdf/GUIRoleTaxonomy#"\n\txmlns:waistate="http://www.w3.org/2005/07/aaa" lang="en" xml:lang="en" class="ggds">\n\t<head>\n\t\t\t\t\n\t\t\t<title>\n\t\t\t\tDyson - Vacuums &amp; Cleaners - The Good Guys\n\t\t\t</title>\n\t\t\t<meta name="description" content="Shop Dyson Vacuums &amp; Cleaners online. The Good Guys stock all the best Dyson Vacuums &amp; Cleaners products at the most competitive prices."/>\n\t\t\t<meta name="keywords" content="dyson, dyson vacuum, dyson animal"/>\n\t\t\t<meta name="pageName" content="SearchResultsPage"/>\n\t\t\t\n\t\t    <link rel="canonical" href="https://www.thegoodguys.com.au/dyson/vacuums-and-cleaners" />\n\t\t    \n\t\t\t    \t<link rel="next" href="https://www.thegoodguys.com.au/dyson/vacuums-and-cleaners?page=2" />\n\t\t\t    <!-- Include script files --><!-- BEGIN CommonJSToInclude.jspf -->\n\n<script src="https://cdn.jsdelivr.net/npm/intersection-observer@0.7.0/intersection-observer.min.js"></script>\n<script src="https://thegoodguys.sirv.com/Content/js/lazyload.min.js"></script>\n\n<!--[if IE]> -->\n<script src="https://cdn.jsdelivr.net/npm/es6-object-assign@1.1.0/dist/object-assign-auto.min.js"></script>\n<!-- [endif]-->\n<link rel="preconnect" href="https://thegoodguys.sirv.com" crossorigin>\n<link rel="preconnect" href="https://www.google.com">\n<link rel="preconnect" href="https://www.google.com.au">\n<link rel="preconnect" href="https://googleads.g.doubleclick.net">\n<link rel="preconnect" href="https://www.googletagmanager.com">\n<link rel="preconnect" href="https://stats.g.doubleclick.net">\n\n<link rel="dns-prefetch" href="//thegoodguys.sirv.com">\n\n\n\t<script src="https://js.braintreegateway.com/web/3.81.0/js/paypal-checkout.min.js"></script>\n\t<script src="https://js.braintreegateway.com/web/3.81.0/js/client.min.js"></script>\n\t<script src="https://js.braintreegateway.com/web/3.81.0/js/data-collector.min.js"></script>\n\n\t\t<script src="https://www.paypal.com/sdk/js?client-id=AZUF61VBiQIUxD_GjSqGRU8q4kMwy3zKRhUWWbn5M2ExA7hjQf6llCuH57NbRy8koYjjZ6Dy31_AgJMc&currency=AUD&components=messages,buttons,funding-eligibility&disable-funding=card&enable-funding=paylater&commit=true&intent=capture"></script>\n\t\t\n<script type="text/javascript" src="/wcsstore/AUOnlineSAS/javascript/BTPayPal.js"></script>\n\n\n\n\n\n<script type="text/javascript" charset="UTF-8" src="/wcsstore/dojo18/dojo/dojo.js" djConfig="parseOnLoad: true, isDebug: false,  modulePaths: {storetext: \'/wcsstore/AUOnlineSAS\'}, useCommentedJson: true,locale: \'en-us\' "></script>\n<script type="text/javascript" charset="UTF-8" src="/wcsstore/dojo18/dojo/dojodesktop-rwd.js" djConfig="parseOnLoad: true, isDebug: false,  modulePaths: {storetext: \'/wcsstore/AUOnlineSAS\'}, useCommentedJson: true,locale: \'en-us\' "></script>\n\n\n<meta name="CommerceSearch" content="storeId_900" />\n<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">\n<link rel="shortcut icon" type="image/x-icon" href="//thegoodguys.sirv.com/icons/favicon.ico?profile=bce" />\n<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="//thegoodguys.sirv.com/icons/apple-touch-icon.png?profile=bce">\n<link rel="apple-touch-icon" type="image/png" sizes="152x152" href="//thegoodguys.sirv.com/icons/favicon-152x152.png?profile=bce">\n<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="//thegoodguys.sirv.com/icons/favicon-120x120.png?profile=bce">\n<link rel="icon" type="image/png" sizes="32x32" href="//thegoodguys.sirv.com/icons/favicon-32x32.png?profile=bce">\n<link rel="icon" type="image/png" sizes="194x194" href="//thegoodguys.sirv.com/icons/favicon-194x194.png?profile=bce">\n<link rel="icon" type="image/png" sizes="192x192" href="//thegoodguys.sirv.com/icons/android-chrome-192x192.png?profile=bce">\n<link rel="icon" type="image/png" sizes="16x16" href="//thegoodguys.sirv.com/icons/favicon-16x16.png?profile=bce">\n<link rel="manifest" href="//thegoodguys.sirv.com/icons/site.webmanifest">\n<link rel="mask-icon" href="//thegoodguys.sirv.com/icons/safari-pinned-tab.svg?profile=bce" color="#5bbad5">\n<meta name="msapplication-TileColor" content="#da532c">\n<meta name="msapplication-TileImage" content="//thegoodguys.sirv.com/icons/mstile-144x144.png?profile=bce">\n<meta name="theme-color" content="#ffffff">\n\n<script type="text/javascript">\n//Redirect to HTTPS request in the browser when detect that using HTTP request,\n//since HTTP request is no longer supported in v9.\nvar httpsProtocol = "https:";\nvar securedPort = \'\';\nif (window.location.protocol != httpsProtocol){\n\tvar href = httpsProtocol + window.location.href.substring(window.location.protocol.length);\n\tvar host = window.location.host;\n\tvar hostname = window.location.hostname;\n\tvar httpsHost = httpsHost = (securedPort != "" && securedPort != null) ? hostname + ":" + securedPort : hostname;\n\thref = href.replace(host, httpsHost);\n\twindow.location.href = href;\n}\n</script>\n\n \n\t\t<script type="text/javascript">\n\t\t\tvar WCParamJS={storeId:\'900\',catalogId:\'30000\',langId:\'-1\',pageView:\'\',orderBy:\'\',orderByContent:\'\',searchTerm:\'\',productId:\'\',uniqueId:\'\',productInventoryFlag:\'\',partNumber:\'\'},absoluteURL="https://www.thegoodguys.com.au/",imageDirectoryPath="/wcsstore/AUOnlineSAS/",styleDirectoryPath="images/colors/color1/",supportPaymentTypePromotions="false",subsFulfillmentFrequencyAttrName="fulfillmentFrequency",subsPaymentFrequencyAttrName="paymentFrequency",subsTimePeriodAttrName="timePeriod",storeNLS=null,storeUserType="G",ios=\'false\',android=false,multiSessionEnabled=false,inactivityTimeout=1800000,inactivityWarningDialogDisplayTimer=20000,inactivityWarningDialogBuffer=30000,inactivityTimeoutTracker=null,dialogTimeoutTracker=null;function getAbsoluteURL(){if(""!=absoluteURL){var e=document.URL,t="";-1!=e.indexOf("://")&&(t=e.substring(0,e.indexOf("://")));var a="";-1!=absoluteURL.indexOf("://")&&(a=absoluteURL.substring(0,absoluteURL.indexOf("://"))),t!=a&&(absoluteURL=t+absoluteURL.substring(absoluteURL.indexOf("://")))}return absoluteURL}function getImageDirectoryPath(){return imageDirectoryPath}function getStyleDirectoryPath(){return styleDirectoryPath}\n\t\t</script>\n\t\n\t\t\t\t<script type="text/javascript"\n\t\t\t\t\tsrc="/wcsstore/AUOnlineSAS/javascript/dist/tggscripts_hm_cat.min.js?v=2"></script>\n\t\t\t\n<script type="text/javascript" src="/wcsstore/AUOnlineSAS/javascript/Widgets/Search.js"></script>\n<script type="text/javascript" src="/wcsstore/AUOnlineSAS/javascript/Widgets/search_solr_autosuggest.js"></script>\n<script type="text/javascript" src="/wcsstore/AUOnlineSAS/javascript/Widgets/MiniShopCartDisplay/MiniShopCartDisplay.js?v=1"></script>\n<script>\n\tdojo.require("wc.service.common");\n\tdojo.require("dojo.number");\n\tdojo.require("dojo.has");\n</script>\n\n\t\t<script type="text/javascript">\n\t\t\tnull==storeNLS&&(dojo.requireLocalization("storetext","StoreText"),storeNLS=dojo.i18n.getLocalization("storetext","StoreText")),initializeInactivityWarning();var ie6=!1,ie7=!1,ie8=!1;null!=navigator&&null!=navigator.userAgent&&(ie6=navigator.userAgent.toLowerCase().indexOf("msie 6.0")>-1,ie7=navigator.userAgent.toLowerCase().indexOf("msie 7.0")>-1,ie8=navigator.userAgent.toLowerCase().indexOf("msie 8.0")>-1),-1==location.href.indexOf("UnsupportedBrowserErrorView")&&(ie6||ie7||ie8)&&document.write(\'<meta http-equiv="Refresh" content="0;URL=https://www.thegoodguys.com.au/UnsupportedBrowserErrorView?catalogId=20000&amp;storeId=900&amp;langId=-1"/>\'),$(document).ready(function(){shoppingActionsJS.setCommonParameters(\'-1\',\'900\',\'30000\',\'G\',\'$\'),shoppingActionsServicesDeclarationJS.setCommonParameters(\'-1\',\'900\',\'30000\');var e=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor),o=/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor);if(e||o)for(var t=dojo.query(\'input[type="hidden"]\'),r=0;r<t.length;r++)t[r].autocomplete="off";(dojo.has("ios")||dojo.has("android"))&&dojo.attr(dojo.body(),"data-wc-device","mobile"),shoppingActionsJS._num_holidays_2_consider=4,shoppingActionsJS._set_store_check()});\n\t\t</script>\t\n\t\n<script type="text/javascript">\n\t \n</script>\n\n<script wid="3da04b88-d810-ea11-828b-00155da08c22" src="https://cdn.particularaudience.com/js/tgg/t.js" defer></script>\n\n<link rel="stylesheet" href="https://use.typekit.net/xxm5tsp.css">\n<!--Start Pre load font -->\n<link rel="preload" as="font" href="https://use.typekit.net/af/2cd6bf/00000000000000000001008f/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&fvd=n5&v=3" type="font/woff2" crossorigin>\n<link rel="preload" as="font" href="https://use.typekit.net/af/309dfe/000000000000000000010091/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&fvd=n7&v=3" type="font/woff2" crossorigin>\n<link rel="preload" as="font" href="https://use.typekit.net/af/9b05f3/000000000000000000013365/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&fvd=n4&v=3" type="font/woff2" crossorigin>\n<link rel="preload" as="font" href="https://use.typekit.net/af/ae4f6c/000000000000000000010096/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&fvd=n3&v=3" type="font/woff2" crossorigin>\n<link rel="preload" as="font" href="https://use.typekit.net/af/0c71d1/000000000000000000010097/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&fvd=n8&v=3" type="font/woff2" crossorigin>\n<link rel="preload" as="font" href="https://thegoodguys.sirv.com/Content/font/compactash-woff.woff?profile=bce" type="font/woff" crossorigin>\n<link rel="preload" as="font" href="https://thegoodguys.sirv.com/Content/font/ggds-iconfont-ttf-update-2019-jun.ttf?profile=bce" type="font/ttf" crossorigin>\n<!-- End Pre load font -->\n\t<link rel="stylesheet" href="/wcsstore/AUOnlineSAS/css/global.ggds.css?v=17.0">\n\t\n\t\t\t<link rel="stylesheet" href="/wcsstore/AUOnlineSAS/css/category-brand.ggds.css">\n\t\t<!--Begin EMarketingSpot.jsp --><!-- BEGIN ContentRecommendation.jsp --><!-- JSPs References: HomePage.jsp, BundleDisplay.jsp , CategoryNavigationDisplay.jsp, CompareProductsDisplay.jsp\n\t\t\t\t\t  DynamicKitDisplay.jsp, PackageDisplay.jsp, ProductDisplay.jsp, \n\t\t\t\t\t  SearchResultDisplay.jsp, SubCategoryPage.jsp, TopCategoryPage.jsp\n\t\t\t\t\t   , Footer.jsp , OrderCancelNotify.jsp , OrderCreateNotify.jsp\n\t\t\t\t\t  OrderShipmentNotify.jsp, AccountActivationNotify.jsp, PasswordChangeNotify.jsp,\n\t\t\t\t\t  PasswordResetNotify.jsp, WishlistCreateNotify.jsp,  LandingPage.jsp, \t\n\t\t\t\t\t  ShippingDetailDisplay.jsp, ShopCartDisplay.jsp, StaticContent, \n\t\t\t\t\t  Static JSPs, Footer_UI.jsp, Header_UI.jsp, ProductDescription_UI.jsp  \n\t\t\t\t\t  UserTime--><!-- END ContentRecommendation.jsp --><!-- BEGIN CategoryRecommendation.jsp --><!-- END CategoryRecommendation.jsp --><!-- BEGIN CatalogEntryRecommendation.jsp -->\n\t\t<script type="text/javascript">\n\t\t\twc.render.declareRefreshController({id:"prodRecommendationRefresh_controller_POC_CommonStaticContentEspot",renderContext:wc.render.getContextById("searchBasedNavigation_context"),url:"",formId:"",renderContextChangedHandler:function(e,r){var o=this.renderContext,t=o.properties.resultType;"products"!=t&&"both"!=t||(r.refresh(o.properties),console.log("espot refreshing"))},postRefreshHandler:function(e){this.renderContext;cursor_clear();var r=this.url,o="",t=r.indexOf("emsName=",0);if(t>=0&&(o=r.substring(t+8)).indexOf("&")>=0&&(o="script_"+(o=o.substring(0,o.indexOf("&")))),""!=o&&null!=dojo.byId(o)){var n=dojo.query(".genericESpot",dojo.byId(o).parentNode)[0];null!=n&&dojo.addClass(n,"emptyESpot")}dojo.publish("CMPageRefreshEvent")}});\n\t\t</script>\n\t<!-- END CatalogEntryRecommendation.jsp --><!--End EMarketingSpot.jsp --><!-- END CommonJSToInclude.jspf -->\n\t\t\t<script type="text/javascript" src="/wcsstore/Widgets/com.ibm.commerce.store.widgets.CatalogEntryList/javascript/SearchBasedNavigationDisplay.js"></script>\n\t\t\t<!-- BEGIN CommonGTMScriptToIncludeExt.jspf --><!-- Google Tag Manager -->\n\t<script>\n\t\tdataLayer=[{pageTitle:\'BrandCategory\',visitorLoginState:\'G\'}];\n\t</script>\n\n<script>\n   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\': new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);})(window,document,\'script\',\'dataLayer\',\'GTM-2DP2\');\n</script>\n<!-- END CommonGTMScriptToIncludeExt.jspf --> \n\t\n<script>(window.BOOMR_mq=window.BOOMR_mq||[]).push(["addVar",{"rua.upush":"false","rua.cpush":"false","rua.upre":"false","rua.cpre":"false","rua.uprl":"false","rua.cprl":"false","rua.cprf":"false","rua.trans":"","rua.cook":"false","rua.ims":"false","rua.ufprl":"false","rua.cfprl":"false","rua.isuxp":"false","rua.texp":"norulematch"}]);</script>\n                              <script>!function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if("False"=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="FDG2S-ZF4G5-GC36U-WAE4Z-YFXRD",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,_,o,r=document.createElement("iframe");if(a[t])a[t]("load",n,!1);else if(a.attachEvent)a.attachEvent("onload",n);r.src="javascript:void(0)",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="width:0;height:0;border:0;display:none;",o=document.getElementsByTagName("script")[0],o.parentNode.insertBefore(r,o);try{_=r.contentWindow.document}catch(O){i=document.domain,r.src="javascript:var d=document.open();d.domain=\'"+i+"\';void(0);",_=r.contentWindow.document}_.open()._l=function(){var a=this.createElement("script");if(i)this.domain=i;a.id="boomr-if-as",a.src=e+"FDG2S-ZF4G5-GC36U-WAE4Z-YFXRD",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},_.write("<bo"+\'dy onload="document._l();">\'),_.close()}}(),"".length>0)if(a&&"performance"in a&&a.performance&&"function"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e=""=="true"?1:0,t="",n="n2xeoyixy5cmczh4rjzq-f-4d40abefd-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,_={"ak.v":"36","ak.cp":"702210","ak.ai":parseInt("459134",10),"ak.ol":"0","ak.cr":16,"ak.ipv":4,"ak.proto":"h2","ak.rid":"37d4c98","ak.r":37441,"ak.a2":e,"ak.m":"a","ak.n":"essl","ak.bpcip":"110.174.71.0","ak.cport":14239,"ak.gh":"23.199.68.189","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"","ak.t":"1694272115","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==fE03RhOkcmjmhONMQTRG4tgRUB3YiUYd52rEOQoMdFZN7Xkuq5PYpVU1HH2Dw+D0ivkUbneAFEKvpgKbSXTRxuRRH3E6j+dicVoCnUleewtejGDV6WQYB+Z4I7rfBeclCBAp8WNkRSQNuvMkWkYXjyh1c4DYbOMmu6CL21/KcYDG0mII6USGQKeckF+EgHhnzw0m9feuX2VJH7n5LSo5H7kn9bn1s2ktgzPHGDJN6ioX4goNcwNa6pJAbKurdbTO8nr7ZPBog/0o+mHUI7Mf0c9O2aL6GWZQ+bagzz4H8F7mFygT0aAABcN/zJRPwkeMou9sGx0lRfMQHOhaHO0I5Uez6R6+J5R9zGuG8kp7YRqN0/REnGRJH1lHYwxKUBlHRdPWlLW43Rqe408PqPYQsooxPy5hZiPrVIPGlTKKdyw=","ak.pv":"29","ak.dpoabenc":"","ak.tf":i};if(""!==t)_["ak.ruds"]=t;var o={i:!1,av:function(e){var t="http.initiator";if(e&&(!e[t]||"spa_hard"===e[t]))_["ak.feo"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(_)},rv:function(){var a=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:_,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a("before_beacon",o.av,null,null),a("onbeacon",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script></head>\n\t<body>\n\t<!-- BEGIN ProductQuiz Script  -->\n\t\t\t\t\t<script type="text/javascript"> \n\t\t\t\t\t\t var productquiz = {\n\t\t\t\t\t\t\tpagetype : \'brandL1category\',\n\t\t\t\t\t\t\tbrand: \'Dyson\',\n\t\t\t\t\t\t\tcategoryid : \'11\'\n\t\t\t\t\t\t }; \n\t\t\t\t\t\t var pageTitleForPagination = \'Dyson - Vacuums & Cleaners - The Good Guys\';\n\t\t\t\t\t</script>\n\t\t\t<!-- END ProductQuiz Script --><!-- BEGIN CommonGTMScriptToInclude.jspf --><!-- Google Tag Manager -->\n<style>\n.async-hide {\n\topacity: 0 !important\n}\n</style>\n\n<noscript>\n\t<iframe src="//www.googletagmanager.com/ns.html?id=GTM-2DP2" height="0" width="0" style="display: none; visibility: hidden"></iframe>\n</noscript>\n<!-- End Google Tag Manager --><!-- END CommonGTMScriptToInclude.jspf --><!-- BEGIN CommonJSPFToInclude.jspf --><!-- BEGIN ProgressBar.jspf -->\n<div id="progress_bar_dialog" dojoType="dijit.Dialog" style="display: none;">\n\t<div id="progress_bar">\n\t\t<div id="loading_popup">\n\t\t\t<div class="top_left" id="WC_StoreCommonUtilities_div_1"><img class="lazy" data-src="https://thegoodguys.sirv.com/image/transparent.gif?profile=bce" alt="No image available"/></div>\n\t\t        <div class="top_right" id="WC_StoreCommonUtilities_div_2"><img class="lazy" data-src="https://thegoodguys.sirv.com/image/transparent.gif?profile=bce" alt="No image available"/></div>\n\t\t        <div class="header" id="WC_StoreCommonUtilities_div_3"></div>\n\t\t        <div class="bodyarea" id="WC_StoreCommonUtilities_div_4">\n\t\t\t\t<div class="bodycontent" id="WC_StoreCommonUtilities_div_5">\n\t\t\t\t\t<img class="lazy" data-src="https://thegoodguys.sirv.com/image/ajax-loader.gif?profile=bce" width="34" height="46" border="0" alt="Your request is being processed."/>\n\t\t\t        </div>\n\t\t\t</div>\n\t\t\t<div class="footer" id="WC_StoreCommonUtilities_div_6">\n\t\t\t\t <div class="bot_left" id="WC_StoreCommonUtilities_div_7"></div>\n\t\t\t\t <div class="bot_right" id="WC_StoreCommonUtilities_div_8"></div>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n<!-- END ProgressBar.jspf --><!-- BEGIN MessageDisplay.jspf -->\n\n<span class="spanacce" style="display:none" id="MessageArea_ACCE_Title">Message Dialog</span>\n<div id="MessageArea" class="store_message" role="alert" aria-labelledby="MessageArea_ACCE_Title">\n\t<div id="msgpopup_content_wrapper" class="content">\n\t\t<a id="clickableErrorMessageImg" role="button" class="close tlignore" href="JavaScript:MessageHelper.hideMessageArea();" title="Close">\n\t\t\t<div class="close_text">Close</div>\n\t\t\t<div class="close_icon"></div>\n\t\t\t<div class="clear_float"></div>\n\t\t</a>\n\t\t\n\t\t<div class="clear_float"></div>\n\t\t\n\t\t<div class="message">\n\t\t\t<div class="message_icon">\n\t\t\t\t<i id="error_icon" style="display:none; color: #DD5353;" class="error_icon ggdsicon-circle-times text-danger"></i>\n\t\t\t\t<i id="success_icon" style="display:none; color: #59C86B;" class="error_icon text-success ggdsicon-circle-tick"></i>\n\t\t\t</div>\n\t\t\t<div class="message_text" role="region" aria-required="true" aria-labelledby="MessageArea">\n\t\t\t\t<span id="ErrorMessageText">\n\t\t\t\t\t\n\t\t\t\t</span>\n\t\t\t</div>\n\t\t\t<div class="clear_float"></div>\n\t\t</div>\t\t\n\t</div>\n</div>\n<span class="spanacce" id="ariaMessage_ACCE_Label" style="display:none">Display Update Message</span>\n<span class="spanacce" role="region" aria-labelledby="ariaMessage_ACCE_Label" id="ariaMessage" aria-live="assertive" aria-atomic="true" aria-relevant="additions"></span>\n<!-- END MessageDisplay.jspf -->\n\n\t<div id="widget_product_comparison_popup" class="customPopUp" dojoType="dijit.Dialog" closeOnTimeOut="false" title="Product Comparison" style="display:none">\n\t\t<div class="widget_product_comparison_popup widget_site_popup">

In [5]:
#html = "https://www.thegoodguys.com.au/vax/vacuums-and-cleaners"
#https://www.thegoodguys.com.au/dyson/vacuums-and-cleaners#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&minHeight:undefined&maxHeight:undefined&minWidth:undefined&maxWidth:undefined&minDepth:undefined&maxDepth:undefined&pageSize:60&

In [6]:
soup = BeautifulSoup(html_string)

In [7]:
print(soup.prettify())

<!DOCTYPE HTML>
<html class="ggds" lang="en" xml:lang="en" xmlns:wairole="http://www.w3.org/2005/01/wai-rdf/GUIRoleTaxonomy#" xmlns:waistate="http://www.w3.org/2005/07/aaa">
 <head>
  <title>
   Dyson - Vacuums &amp; Cleaners - The Good Guys
  </title>
  <meta content="Shop Dyson Vacuums &amp; Cleaners online. The Good Guys stock all the best Dyson Vacuums &amp; Cleaners products at the most competitive prices." name="description"/>
  <meta content="dyson, dyson vacuum, dyson animal" name="keywords"/>
  <meta content="SearchResultsPage" name="pageName"/>
  <link href="https://www.thegoodguys.com.au/dyson/vacuums-and-cleaners" rel="canonical"/>
  <link href="https://www.thegoodguys.com.au/dyson/vacuums-and-cleaners?page=2" rel="next"/>
  <!-- Include script files -->
  <!-- BEGIN CommonJSToInclude.jspf -->
  <script src="https://cdn.jsdelivr.net/npm/intersection-observer@0.7.0/intersection-observer.min.js">
  </script>
  <script src="https://thegoodguys.sirv.com/Content/js/lazyload.min.js">
  </script>
  <!--[if IE]> -->
  <script src="https://cdn.jsdelivr.net/npm/es6-object-assign@1.1.0/dist/object-assign-auto.min.js">
  </script>
  <!-- [endif]-->
  <link crossorigin="" href="https://thegoodguys.sirv.com" rel="preconnect"/>
  <link href="https://www.google.com" rel="preconnect"/>
  <link href="https://www.google.com.au" rel="preconnect"/>
  <link href="https://googleads.g.doubleclick.net" rel="preconnect"/>
  <link href="https://www.googletagmanager.com" rel="preconnect"/>
  <link href="https://stats.g.doubleclick.net" rel="preconnect"/>
  <link href="//thegoodguys.sirv.com" rel="dns-prefetch"/>
  <script src="https://js.braintreegateway.com/web/3.81.0/js/paypal-checkout.min.js">
  </script>
  <script src="https://js.braintreegateway.com/web/3.81.0/js/client.min.js">
  </script>
  <script src="https://js.braintreegateway.com/web/3.81.0/js/data-collector.min.js">
  </script>
  <script src="https://www.paypal.com/sdk/js?client-id=AZUF61VBiQIUxD_GjSqGRU8q4kMwy3zKRhUWWbn5M2ExA7hjQf6llCuH57NbRy8koYjjZ6Dy31_AgJMc&amp;currency=AUD&amp;components=messages,buttons,funding-eligibility&amp;disable-funding=card&amp;enable-funding=paylater&amp;commit=true&amp;intent=capture">
  </script>
  <script src="/wcsstore/AUOnlineSAS/javascript/BTPayPal.js" type="text/javascript">
  </script>
  <script charset="UTF-8" djconfig="parseOnLoad: true, isDebug: false,  modulePaths: {storetext: '/wcsstore/AUOnlineSAS'}, useCommentedJson: true,locale: 'en-us' " src="/wcsstore/dojo18/dojo/dojo.js" type="text/javascript">
  </script>
  <script charset="UTF-8" djconfig="parseOnLoad: true, isDebug: false,  modulePaths: {storetext: '/wcsstore/AUOnlineSAS'}, useCommentedJson: true,locale: 'en-us' " src="/wcsstore/dojo18/dojo/dojodesktop-rwd.js" type="text/javascript">
  </script>
  <meta content="storeId_900" name="CommerceSearch"/>
  <meta content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
  <link href="//thegoodguys.sirv.com/icons/favicon.ico?profile=bce" rel="shortcut icon" type="image/x-icon"/>
  <link href="//thegoodguys.sirv.com/icons/apple-touch-icon.png?profile=bce" rel="apple-touch-icon" sizes="180x180" type="image/png"/>
  <link href="//thegoodguys.sirv.com/icons/favicon-152x152.png?profile=bce" rel="apple-touch-icon" sizes="152x152" type="image/png"/>
  <link href="//thegoodguys.sirv.com/icons/favicon-120x120.png?profile=bce" rel="apple-touch-icon" sizes="120x120" type="image/png"/>
  <link href="//thegoodguys.sirv.com/icons/favicon-32x32.png?profile=bce" rel="icon" sizes="32x32" type="image/png"/>
  <link href="//thegoodguys.sirv.com/icons/favicon-194x194.png?profile=bce" rel="icon" sizes="194x194" type="image/png"/>
  <link href="//thegoodguys.sirv.com/icons/android-chrome-192x192.png?profile=bce" rel="icon" sizes="192x192" type="image/png"/>
  <link href="//thegoodguys.sirv.com/icons/favicon-16x16.png?profile=bce" rel="icon" sizes="16x16" type="image/png"/>
  <link href="//thegoodguys.sirv.com/icons/site.webmanifest" rel="manifest"/>
  <link color="#5bbad5" href="//thegoodguys.sirv.com/icons/safari-pinned-tab.svg?profile=bce" rel="mask-icon"/>
  <meta content="#da532c" name="msapplication-TileColor"/>
  <meta content="//thegoodguys.sirv.com/icons/mstile-144x144.png?profile=bce" name="msapplication-TileImage"/>
  <meta content="#ffffff" name="theme-color"/>
  <script type="text/javascript">
   //Redirect to HTTPS request in the browser when detect that using HTTP request,
//since HTTP request is no longer supported in v9.
var httpsProtocol = "https:";
var securedPort = '';
if (window.location.protocol != httpsProtocol){
	var href = httpsProtocol + window.location.href.substring(window.location.protocol.length);
	var host = window.location.host;
	var hostname = window.location.hostname;
	var httpsHost = httpsHost = (securedPort != "" && securedPort != null) ? hostname + ":" + securedPort : hostname;
	href = href.replace(host, httpsHost);
	window.location.href = href;
}
  </script>
  <script type="text/javascript">
   var WCParamJS={storeId:'900',catalogId:'30000',langId:'-1',pageView:'',orderBy:'',orderByContent:'',searchTerm:'',productId:'',uniqueId:'',productInventoryFlag:'',partNumber:''},absoluteURL="https://www.thegoodguys.com.au/",imageDirectoryPath="/wcsstore/AUOnlineSAS/",styleDirectoryPath="images/colors/color1/",supportPaymentTypePromotions="false",subsFulfillmentFrequencyAttrName="fulfillmentFrequency",subsPaymentFrequencyAttrName="paymentFrequency",subsTimePeriodAttrName="timePeriod",storeNLS=null,storeUserType="G",ios='false',android=false,multiSessionEnabled=false,inactivityTimeout=1800000,inactivityWarningDialogDisplayTimer=20000,inactivityWarningDialogBuffer=30000,inactivityTimeoutTracker=null,dialogTimeoutTracker=null;function getAbsoluteURL(){if(""!=absoluteURL){var e=document.URL,t="";-1!=e.indexOf("://")&&(t=e.substring(0,e.indexOf("://")));var a="";-1!=absoluteURL.indexOf("://")&&(a=absoluteURL.substring(0,absoluteURL.indexOf("://"))),t!=a&&(absoluteURL=t+absoluteURL.substring(absoluteURL.indexOf("://")))}return absoluteURL}function getImageDirectoryPath(){return imageDirectoryPath}function getStyleDirectoryPath(){return styleDirectoryPath}
  </script>
  <script src="/wcsstore/AUOnlineSAS/javascript/dist/tggscripts_hm_cat.min.js?v=2" type="text/javascript">
  </script>
  <script src="/wcsstore/AUOnlineSAS/javascript/Widgets/Search.js" type="text/javascript">
  </script>
  <script src="/wcsstore/AUOnlineSAS/javascript/Widgets/search_solr_autosuggest.js" type="text/javascript">
  </script>
  <script src="/wcsstore/AUOnlineSAS/javascript/Widgets/MiniShopCartDisplay/MiniShopCartDisplay.js?v=1" type="text/javascript">
  </script>
  <script>
   dojo.require("wc.service.common");
	dojo.require("dojo.number");
	dojo.require("dojo.has");
  </script>
  <script type="text/javascript">
   null==storeNLS&&(dojo.requireLocalization("storetext","StoreText"),storeNLS=dojo.i18n.getLocalization("storetext","StoreText")),initializeInactivityWarning();var ie6=!1,ie7=!1,ie8=!1;null!=navigator&&null!=navigator.userAgent&&(ie6=navigator.userAgent.toLowerCase().indexOf("msie 6.0")>-1,ie7=navigator.userAgent.toLowerCase().indexOf("msie 7.0")>-1,ie8=navigator.userAgent.toLowerCase().indexOf("msie 8.0")>-1),-1==location.href.indexOf("UnsupportedBrowserErrorView")&&(ie6||ie7||ie8)&&document.write('<meta http-equiv="Refresh" content="0;URL=https://www.thegoodguys.com.au/UnsupportedBrowserErrorView?catalogId=20000&amp;storeId=900&amp;langId=-1"/>'),$(document).ready(function(){shoppingActionsJS.setCommonParameters('-1','900','30000','G','$'),shoppingActionsServicesDeclarationJS.setCommonParameters('-1','900','30000');var e=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor),o=/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor);if(e||o)for(var t=dojo.query('input[type="hidden"]'),r=0;r<t.length;r++)t[r].autocomplete="off";(dojo.has("ios")||dojo.has("android"))&&dojo.attr(dojo.body(),"data-wc-device","mobile"),shoppingActionsJS._num_holidays_2_consider=4,shoppingActionsJS._set_store_check()});
  </script>
  <script type="text/javascript">
  </script>
  <script defer="" src="https://cdn.particularaudience.com/js/tgg/t.js" wid="3da04b88-d810-ea11-828b-00155da08c22">
  </script>
  <link href="https://use.typekit.net/xxm5tsp.css" rel="stylesheet"/>
  <!--Start Pre load font -->
  <link as="font" crossorigin="" href="https://use.typekit.net/af/2cd6bf/00000000000000000001008f/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n5&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://use.typekit.net/af/309dfe/000000000000000000010091/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n7&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://use.typekit.net/af/9b05f3/000000000000000000013365/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n4&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://use.typekit.net/af/ae4f6c/000000000000000000010096/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n3&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://use.typekit.net/af/0c71d1/000000000000000000010097/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n8&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://thegoodguys.sirv.com/Content/font/compactash-woff.woff?profile=bce" rel="preload" type="font/woff"/>
  <link as="font" crossorigin="" href="https://thegoodguys.sirv.com/Content/font/ggds-iconfont-ttf-update-2019-jun.ttf?profile=bce" rel="preload" type="font/ttf"/>
  <!-- End Pre load font -->
  <link href="/wcsstore/AUOnlineSAS/css/global.ggds.css?v=17.0" rel="stylesheet"/>
  <link href="/wcsstore/AUOnlineSAS/css/category-brand.ggds.css" rel="stylesheet"/>
  <!--Begin EMarketingSpot.jsp -->
  <!-- BEGIN ContentRecommendation.jsp -->
  <!-- JSPs References: HomePage.jsp, BundleDisplay.jsp , CategoryNavigationDisplay.jsp, CompareProductsDisplay.jsp
					  DynamicKitDisplay.jsp, PackageDisplay.jsp, ProductDisplay.jsp,
					  SearchResultDisplay.jsp, SubCategoryPage.jsp, TopCategoryPage.jsp
					   , Footer.jsp , OrderCancelNotify.jsp , OrderCreateNotify.jsp
					  OrderShipmentNotify.jsp, AccountActivationNotify.jsp, PasswordChangeNotify.jsp,
					  PasswordResetNotify.jsp, WishlistCreateNotify.jsp,  LandingPage.jsp,
					  ShippingDetailDisplay.jsp, ShopCartDisplay.jsp, StaticContent,
					  Static JSPs, Footer_UI.jsp, Header_UI.jsp, ProductDescription_UI.jsp
					  UserTime-->
  <!-- END ContentRecommendation.jsp -->
  <!-- BEGIN CategoryRecommendation.jsp -->
  <!-- END CategoryRecommendation.jsp -->
  <!-- BEGIN CatalogEntryRecommendation.jsp -->
  <script type="text/javascript">
   wc.render.declareRefreshController({id:"prodRecommendationRefresh_controller_POC_CommonStaticContentEspot",renderContext:wc.render.getContextById("searchBasedNavigation_context"),url:"",formId:"",renderContextChangedHandler:function(e,r){var o=this.renderContext,t=o.properties.resultType;"products"!=t&&"both"!=t||(r.refresh(o.properties),console.log("espot refreshing"))},postRefreshHandler:function(e){this.renderContext;cursor_clear();var r=this.url,o="",t=r.indexOf("emsName=",0);if(t>=0&&(o=r.substring(t+8)).indexOf("&")>=0&&(o="script_"+(o=o.substring(0,o.indexOf("&")))),""!=o&&null!=dojo.byId(o)){var n=dojo.query(".genericESpot",dojo.byId(o).parentNode)[0];null!=n&&dojo.addClass(n,"emptyESpot")}dojo.publish("CMPageRefreshEvent")}});
  </script>
  <!-- END CatalogEntryRecommendation.jsp -->
  <!--End EMarketingSpot.jsp -->
  <!-- END CommonJSToInclude.jspf -->
  <script src="/wcsstore/Widgets/com.ibm.commerce.store.widgets.CatalogEntryList/javascript/SearchBasedNavigationDisplay.js" type="text/javascript">
  </script>
  <!-- BEGIN CommonGTMScriptToIncludeExt.jspf -->
  <!-- Google Tag Manager -->
  <script>
   dataLayer=[{pageTitle:'BrandCategory',visitorLoginState:'G'}];
  </script>
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-2DP2');
  </script>
  <!-- END CommonGTMScriptToIncludeExt.jspf -->
  <script>
   (window.BOOMR_mq=window.BOOMR_mq||[]).push(["addVar",{"rua.upush":"false","rua.cpush":"false","rua.upre":"false","rua.cpre":"false","rua.uprl":"false","rua.cprl":"false","rua.cprf":"false","rua.trans":"","rua.cook":"false","rua.ims":"false","rua.ufprl":"false","rua.cfprl":"false","rua.isuxp":"false","rua.texp":"norulematch"}]);
  </script>
  <script>
   !function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if("False"=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="FDG2S-ZF4G5-GC36U-WAE4Z-YFXRD",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,_,o,r=document.createElement("iframe");if(a[t])a[t]("load",n,!1);else if(a.attachEvent)a.attachEvent("onload",n);r.src="javascript:void(0)",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="width:0;height:0;border:0;display:none;",o=document.getElementsByTagName("script")[0],o.parentNode.insertBefore(r,o);try{_=r.contentWindow.document}catch(O){i=document.domain,r.src="javascript:var d=document.open();d.domain='"+i+"';void(0);",_=r.contentWindow.document}_.open()._l=function(){var a=this.createElement("script");if(i)this.domain=i;a.id="boomr-if-as",a.src=e+"FDG2S-ZF4G5-GC36U-WAE4Z-YFXRD",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},_.write("<bo"+'dy onload="document._l();">'),_.close()}}(),"".length>0)if(a&&"performance"in a&&a.performance&&"function"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e=""=="true"?1:0,t="",n="n2xeoyixy5cmczh4rjzq-f-4d40abefd-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,_={"ak.v":"36","ak.cp":"702210","ak.ai":parseInt("459134",10),"ak.ol":"0","ak.cr":16,"ak.ipv":4,"ak.proto":"h2","ak.rid":"37d4c98","ak.r":37441,"ak.a2":e,"ak.m":"a","ak.n":"essl","ak.bpcip":"110.174.71.0","ak.cport":14239,"ak.gh":"23.199.68.189","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"","ak.t":"1694272115","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==fE03RhOkcmjmhONMQTRG4tgRUB3YiUYd52rEOQoMdFZN7Xkuq5PYpVU1HH2Dw+D0ivkUbneAFEKvpgKbSXTRxuRRH3E6j+dicVoCnUleewtejGDV6WQYB+Z4I7rfBeclCBAp8WNkRSQNuvMkWkYXjyh1c4DYbOMmu6CL21/KcYDG0mII6USGQKeckF+EgHhnzw0m9feuX2VJH7n5LSo5H7kn9bn1s2ktgzPHGDJN6ioX4goNcwNa6pJAbKurdbTO8nr7ZPBog/0o+mHUI7Mf0c9O2aL6GWZQ+bagzz4H8F7mFygT0aAABcN/zJRPwkeMou9sGx0lRfMQHOhaHO0I5Uez6R6+J5R9zGuG8kp7YRqN0/REnGRJH1lHYwxKUBlHRdPWlLW43Rqe408PqPYQsooxPy5hZiPrVIPGlTKKdyw=","ak.pv":"29","ak.dpoabenc":"","ak.tf":i};if(""!==t)_["ak.ruds"]=t;var o={i:!1,av:function(e){var t="http.initiator";if(e&&(!e[t]||"spa_hard"===e[t]))_["ak.feo"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(_)},rv:function(){var a=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:_,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a("before_beacon",o.av,null,null),a("onbeacon",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);
  </script>
 </head>
 <body>
  <!-- BEGIN ProductQuiz Script  -->
  <script type="text/javascript">
   var productquiz = {
							pagetype : 'brandL1category',
							brand: 'Dyson',
							categoryid : '11'
						 };
						 var pageTitleForPagination = 'Dyson - Vacuums & Cleaners - The Good Guys';
  </script>
  <!-- END ProductQuiz Script -->
  <!-- BEGIN CommonGTMScriptToInclude.jspf -->
  <!-- Google Tag Manager -->
  <style>
   .async-hide {
	opacity: 0 !important
}
  </style>
  <noscript>
   <iframe height="0" src="//www.googletagmanager.com/ns.html?id=GTM-2DP2" style="display: none; visibility: hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager -->
  <!-- END CommonGTMScriptToInclude.jspf -->
  <!-- BEGIN CommonJSPFToInclude.jspf -->
  <!-- BEGIN ProgressBar.jspf -->
  <div dojotype="dijit.Dialog" id="progress_bar_dialog" style="display: none;">
   <div id="progress_bar">
    <div id="loading_popup">
     <div class="top_left" id="WC_StoreCommonUtilities_div_1">
      <img alt="No image available" class="lazy" data-src="https://thegoodguys.sirv.com/image/transparent.gif?profile=bce"/>
     </div>
     <div class="top_right" id="WC_StoreCommonUtilities_div_2">
      <img alt="No image available" class="lazy" data-src="https://thegoodguys.sirv.com/image/transparent.gif?profile=bce"/>
     </div>
     <div class="header" id="WC_StoreCommonUtilities_div_3">
     </div>
     <div class="bodyarea" id="WC_StoreCommonUtilities_div_4">
      <div class="bodycontent" id="WC_StoreCommonUtilities_div_5">
       <img alt="Your request is being processed." border="0" class="lazy" data-src="https://thegoodguys.sirv.com/image/ajax-loader.gif?profile=bce" height="46" width="34"/>
      </div>
     </div>
     <div class="footer" id="WC_StoreCommonUtilities_div_6">
      <div class="bot_left" id="WC_StoreCommonUtilities_div_7">
      </div>
      <div class="bot_right" id="WC_StoreCommonUtilities_div_8">
      </div>
     </div>
    </div>
   </div>
  </div>
  <!-- END ProgressBar.jspf -->
  <!-- BEGIN MessageDisplay.jspf -->
  <span class="spanacce" id="MessageArea_ACCE_Title" style="display:none">
   Message Dialog
  </span>
  <div aria-labelledby="MessageArea_ACCE_Title" class="store_message" id="MessageArea" role="alert">
   <div class="content" id="msgpopup_content_wrapper">
    <a class="close tlignore" href="JavaScript:MessageHelper.hideMessageArea();" id="clickableErrorMessageImg" role="button" title="Close">
     <div class="close_text">
      Close
     </div>
     <div class="close_icon">
     </div>
     <div class="clear_float">
     </div>
    </a>
    <div class="clear_float">
    </div>
    <div class="message">
     <div class="message_icon">
      <i class="error_icon ggdsicon-circle-times text-danger" id="error_icon" style="display:none; color: #DD5353;">
      </i>
      <i class="error_icon text-success ggdsicon-circle-tick" id="success_icon" style="display:none; color: #59C86B;">
      </i>
     </div>
     <div aria-labelledby="MessageArea" aria-required="true" class="message_text" role="region">
      <span id="ErrorMessageText">
      </span>
     </div>
     <div class="clear_float">
     </div>
    </div>
   </div>
  </div>
  <span class="spanacce" id="ariaMessage_ACCE_Label" style="display:none">
   Display Update Message
  </span>
  <span aria-atomic="true" aria-labelledby="ariaMessage_ACCE_Label" aria-live="assertive" aria-relevant="additions" class="spanacce" id="ariaMessage" role="region">
  </span>
  <!-- END MessageDisplay.jspf -->
  <div class="customPopUp" closeontimeout="false" dojotype="dijit.Dialog" id="widget_product_comparison_popup" style="display:none" title="Product Comparison">
   <div class="widget_product_comparison_popup widget_site_popup">
    <!-- Top Border Styling -->
    <div class="top">
     <div class="left_border">
     </div>
     <div class="middle">
     </div>
     <div class="right_border">
     </div>
    </div>
    <div class="clear_float">
    </div>

In [8]:
#tag_object_model=soup.find_all('span',{'class':'product-tile-model text-graydark text-nowrap'})
tag_object_model=soup.find_all('div',{'class':'product-tile-main clearfix'})
tag_object_model

[<div class="product-tile-main clearfix">
 <a aria-hidden="true" class="disp-block" href="https://www.thegoodguys.com.au/dyson-v11-cordless-vacuum-419652-01" id="WC_CatalogEntryDBThumbnailDisplayJSPF_3074457345621560170_link_9b" onclick=" GTMTaggingJS.onNewProductClick('50080826','V11 Cordless Vacuum','1197.0','Dyson','Vacuums &amp; Cleaners','BrandCategory','','N/A','DEAL DAYS');
 	" tabindex="-1" title="Dyson V11 Cordless Vacuum">
 <h4 class="product-tile-name">Dyson V11 Cordless Vacuum</h4>
 </a>
 <div class="product-tile-info text-size-90">
 <span class="product-tile-model text-graydark text-nowrap">419652-01</span>
 <span class="text-black text-right text-nowrap"></span>
 </div>
 <div class="product-tile-details">
 <div>
 <div class="product-tile__price" id="product_price_3074457345621560170">
 <!-- 				 <div class="col-xs-7 padd-0 pricepoint product_price_dollar"> -->
 <!-- BEGIN PriceDisplay.jspf --><!-- --><!--  promoPriceAttrValID - 8585014    --><!--  promoCampaignName:: DEAL DAYS --><!--  JSON VALUE :: {"amount":"","Campaign":"DEAL DAYS","endDate":"20-SEP-23","startDate":"07-SEP-23"} --><!--  If leverage price rule to get the price, get the contract unit price. --><!-- grid -->
 <div class="product-tile__price-label pricepoint-promolabel-wrap">
 <div class="pricepoint product_price_dollar">
 <div class="pricepoint clearfix padd-right-5">
 <span class="pricepoint-price" id="offerPrice_3074457345621560170">
 <div class="pricepoint-price--promo"><i class="curr">$</i>1197</div>
 </span>
 </div>
 <input id="ProductInfoPrice_3074457345621560170" type="hidden" value="$1197.00"/>
 </div>
 <div class="pricepoint-promolabel-wrap__label">
 <div class="promo-label-wrap">
 <span class="promo-label-ribbon bg-dealdays">DEAL DAYS</span>
 </div>
 </div>
 </div>
 <div class="bg-graylight-5 product-tile-paypal">
 <img class="lazy disp-inline" data-src="https://thegoodguys.sirv.com/Content/BuyNowPayLater/PayPal.svg"/>
 <span class="text-size-90">4 payments of <span class="text-bold">$299.25</span></span>
 </div>
 <!-- END PriceDisplay.jspf --><!--  </div>	 -->
 </div>
 </div>
 <footer class="product-tile-footer">
 <aside class="compare-toggle">
 <div class="compare-toggle-inner clearfix">
 <div class="compare_target compare-toggle-label clearfix" id="compare_3074457345621560170">
 <input id="comparebox_3074457345621560170" name="comparebox_3074457345621560170" onchange="javascript:shoppingActionsJS.addOrRemoveFromCompare('3074457345621560170',this)" onclick="if(this.checked == true){dataLayer.push({'event': 'TGGPD-Req7','TGGPCEventCategory':'Product Compare','TGGPCEventAction':'Add to Compare','TGGPCEventLabel':'50080826'});}" type="checkbox" value="3074457345621560170"/>
 <label for="comparebox_3074457345621560170">Compare</label>
 <a aria-label="Compare" class="compare-toggle-link bg-info-sat" href="javascript:shoppingActionsJS.compareProducts({top_category: '', parent_category_rn: '', categoryId: '11503'});" id="compareButton_3074457345621560170" role="button">Compare</a>
 </div>
 </div>
 </aside>
 <div class="reviews-stars-link" style="margin-left:auto">
 <a class="reviews-stars-link" href="https://www.thegoodguys.com.au/dyson-v11-cordless-vacuum-419652-01#product_rating_box" onclick="javascript:shoppingActionsJS._rtg_rvws_datalayer('TGGRatingsReviews', 'Ratings &amp; Reviews', 'Read Reviews - Listing', '50080826');">
 <div class="reviews-stars-link__stars reviews-stars text-size-115">
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 </div>
 <span class="reviews-stars-link__text-link text-medium marg-left-5">(437)</span></a>
 </div>
 </footer>
 </div>
 </div>,
 <div class="product-tile-main clearfix">
 <a aria-hidden="true" class="disp-block" href="https://www.thegoodguys.com.au/dyson-v8-cordless-vacuum-394437-01" id="WC_CatalogEntryDBThumbnailDisplayJSPF_3074457345621560172_link_9b" onclick=" GTMTaggingJS.onNewProductClick('50080902','V8 Cordless Vacuum','499.0','Dyson','Vacuums &amp; Cleaners','BrandCategory','','N/A','NEW DEAL');
 	" tabindex="-1" title="Dyson V8 Cordless Vacuum">
 <h4 class="product-tile-name">Dyson V8 Cordless Vacuum</h4>
 </a>
 <div class="product-tile-info text-size-90">
 <span class="product-tile-model text-graydark text-nowrap">394437-01</span>
 <span class="text-black text-right text-nowrap"></span>
 </div>
 <div class="product-tile-details">
 <div>
 <div class="product-tile__price" id="product_price_3074457345621560172">
 <!-- 				 <div class="col-xs-7 padd-0 pricepoint product_price_dollar"> -->
 <!-- BEGIN PriceDisplay.jspf --><!-- --><!--  promoPriceAttrValID - 8588010    --><!--  promoCampaignName:: NEW DEAL --><!--  JSON VALUE :: {"amount":"","Campaign":"NEW DEAL","endDate":"20-SEP-23","startDate":"07-SEP-23"} --><!--  If leverage price rule to get the price, get the contract unit price. --><!-- grid -->
 <div class="product-tile__price-label pricepoint-promolabel-wrap">
 <div class="pricepoint product_price_dollar">
 <div class="pricepoint clearfix padd-right-5">
 <span class="pricepoint-price" id="offerPrice_3074457345621560172">
 <div class="pricepoint-price--promo"><i class="curr">$</i>499</div>
 </span>
 </div>
 <input id="ProductInfoPrice_3074457345621560172" type="hidden" value="$499.00"/>
 </div>
 <div class="pricepoint-promolabel-wrap__label">
 <div class="promo-label-wrap">
 <span class="promo-label-ribbon bg-newdeal">NEW DEAL</span>
 </div>
 </div>
 </div>
 <div class="bg-graylight-5 product-tile-paypal">
 <img class="lazy disp-inline" data-src="https://thegoodguys.sirv.com/Content/BuyNowPayLater/PayPal.svg"/>
 <span class="text-size-90">4 payments of <span class="text-bold">$124.75</span></span>
 </div>
 <!-- END PriceDisplay.jspf --><!--  </div>	 -->
 </div>
 </div>
 <footer class="product-tile-footer">
 <aside class="compare-toggle">
 <div class="compare-toggle-inner clearfix">
 <div class="compare_target compare-toggle-label clearfix" id="compare_3074457345621560172">
 <input id="comparebox_3074457345621560172" name="comparebox_3074457345621560172" onchange="javascript:shoppingActionsJS.addOrRemoveFromCompare('3074457345621560172',this)" onclick="if(this.checked == true){dataLayer.push({'event': 'TGGPD-Req7','TGGPCEventCategory':'Product Compare','TGGPCEventAction':'Add to Compare','TGGPCEventLabel':'50080902'});}" type="checkbox" value="3074457345621560172"/>
 <label for="comparebox_3074457345621560172">Compare</label>
 <a aria-label="Compare" class="compare-toggle-link bg-info-sat" href="javascript:shoppingActionsJS.compareProducts({top_category: '', parent_category_rn: '', categoryId: '11503'});" id="compareButton_3074457345621560172" role="button">Compare</a>
 </div>
 </div>
 </aside>
 <div class="reviews-stars-link" style="margin-left:auto">
 <a class="reviews-stars-link" href="https://www.thegoodguys.com.au/dyson-v8-cordless-vacuum-394437-01#product_rating_box" onclick="javascript:shoppingActionsJS._rtg_rvws_datalayer('TGGRatingsReviews', 'Ratings &amp; Reviews', 'Read Reviews - Listing', '50080902');">
 <div class="reviews-stars-link__stars reviews-stars text-size-115">
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star-half-o"></i>
 </div>
 <span class="reviews-stars-link__text-link text-medium marg-left-5">(582)</span></a>
 </div>
 </footer>
 </div>
 </div>,
 <div class="product-tile-main clearfix">
 <a aria-hidden="true" class="disp-block" href="https://www.thegoodguys.com.au/dyson-v7-advanced-cordless-vacuum-419671-01" id="WC_CatalogEntryDBThumbnailDisplayJSPF_3074457345621659168_link_9b" onclick=" GTMTaggingJS.onNewProductClick('50081432','V7 Advanced Cordless Vacuum','399.0','Dyson','Vacuums &amp; Cleaners','BrandCategory','','N/A','NEW DEAL');
 	" tabindex="-1" title="Dyson V7 Advanced Cordless Vacuum">
 <h4 class="product-tile-name">Dyson V7 Advanced Cordless Vacuum</h4>
 </a>
 <div class="product-tile-info text-size-90">
 <span class="product-tile-model text-graydark text-nowrap">419671-01</span>
 <span class="text-black text-right text-nowrap"></span>
 </div>
 <div class="product-tile-details">
 <div>
 <div class="product-tile__price" id="product_price_3074457345621659168">
 <!-- 				 <div class="col-xs-7 padd-0 pricepoint product_price_dollar"> -->
 <!-- BEGIN PriceDisplay.jspf --><!-- --><!--  promoPriceAttrValID - 8505512    --><!--  promoCampaignName:: NEW DEAL --><!--  JSON VALUE :: {"amount":"","Campaign":"NEW DEAL","endDate":"13-SEP-23","startDate":"01-SEP-23"} --><!--  If leverage price rule to get the price, get the contract unit price. --><!-- grid -->
 <div class="product-tile__price-label pricepoint-promolabel-wrap">
 <div class="pricepoint product_price_dollar">
 <div class="pricepoint clearfix padd-right-5">
 <span class="pricepoint-price" id="offerPrice_3074457345621659168">
 <div class="pricepoint-price--promo"><i class="curr">$</i>399</div>
 </span>
 </div>
 <input id="ProductInfoPrice_3074457345621659168" type="hidden" value="$399.00"/>
 </div>
 <div class="pricepoint-promolabel-wrap__label">
 <div class="promo-label-wrap">
 <span class="promo-label-ribbon bg-newdeal">NEW DEAL</span>
 </div>
 </div>
 </div>
 <div class="bg-graylight-5 product-tile-paypal">
 <img class="lazy disp-inline" data-src="https://thegoodguys.sirv.com/Content/BuyNowPayLater/PayPal.svg"/>
 <span class="text-size-90">4 payments of <span class="text-bold">$99.75</span></span>
 </div>
 <!-- END PriceDisplay.jspf --><!--  </div>	 -->
 </div>
 </div>
 <footer class="product-tile-footer">
 <aside class="compare-toggle">
 <div class="compare-toggle-inner clearfix">
 <div class="compare_target compare-toggle-label clearfix" id="compare_3074457345621659168">
 <input id="comparebox_3074457345621659168" name="comparebox_3074457345621659168" onchange="javascript:shoppingActionsJS.addOrRemoveFromCompare('3074457345621659168',this)" onclick="if(this.checked == true){dataLayer.push({'event': 'TGGPD-Req7','TGGPCEventCategory':'Product Compare','TGGPCEventAction':'Add to Compare','TGGPCEventLabel':'50081432'});}" type="checkbox" value="3074457345621659168"/>
 <label for="comparebox_3074457345621659168">Compare</label>
 <a aria-label="Compare" class="compare-toggle-link bg-info-sat" href="javascript:shoppingActionsJS.compareProducts({top_category: '', parent_category_rn: '', categoryId: '11503'});" id="compareButton_3074457345621659168" role="button">Compare</a>
 </div>
 </div>
 </aside>
 <div class="reviews-stars-link" style="margin-left:auto">
 <a class="reviews-stars-link" href="https://www.thegoodguys.com.au/dyson-v7-advanced-cordless-vacuum-419671-01#product_rating_box" onclick="javascript:shoppingActionsJS._rtg_rvws_datalayer('TGGRatingsReviews', 'Ratings &amp; Reviews', 'Read Reviews - Listing', '50081432');">
 <div class="reviews-stars-link__stars reviews-stars text-size-115">
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star-half-o"></i>
 </div>
 <span class="reviews-stars-link__text-link text-medium marg-left-5">(910)</span></a>
 </div>
 </footer>
 </div>
 </div>,
 <div class="product-tile-main clearfix">
 <a aria-hidden="true" class="disp-block" href="https://www.thegoodguys.com.au/dyson-gen5detect-absolute-cordless-vacuum-443066-01" id="WC_CatalogEntryDBThumbnailDisplayJSPF_3074457345621802168_link_9b" onclick=" GTMTaggingJS.onNewProductClick('50082809','Gen5detect Absolute Cordless Vacuum','997.0','Dyson','Vacuums &amp; Cleaners','BrandCategory','','N/A','DEAL DAYS');
 	" tabindex="-1" title="Dyson Gen5detect Absolute Cordless Vacuum">
 <h4 class="product-tile-name">Dyson Gen5detect Absolute Cordless Vacuum</h4>
 </a>
 <div class="product-tile-info text-size-90">
 <span class="product-tile-model text-graydark text-nowrap">443066-01</span>
 <span class="text-black text-right text-nowrap"></span>
 </div>
 <div class="product-tile-details">
 <div>
 <div class="product-tile__price" id="product_price_3074457345621802168">
 <!-- 				 <div class="col-xs-7 padd-0 pricepoint product_price_dollar"> -->
 <!-- BEGIN PriceDisplay.jspf --><!-- --><!--  promoPriceAttrValID - 8541010    --><!--  promoCampaignName:: DEAL DAYS --><!--  JSON VALUE :: {"amount":"","Campaign":"DEAL DAYS","endDate":"20-SEP-23","startDate":"07-SEP-23"} --><!--  If leverage price rule to get the price, get the contract unit price. --><!-- grid -->
 <div class="product-tile__price-label pricepoint-promolabel-wrap">
 <div class="pricepoint product_price_dollar">
 <div class="pricepoint clearfix padd-right-5">
 <span class="pricepoint-price" id="offerPrice_3074457345621802168">
 <div class="pricepoint-price--promo"><i class="curr">$</i>997</div>
 </span>
 </div>
 <input id="ProductInfoPrice_3074457345621802168" type="hidden" value="$997.00"/>
 </div>
 <div class="pricepoint-promolabel-wrap__label">
 <div class="promo-label-wrap">
 <span class="promo-label-ribbon bg-dealdays">DEAL DAYS</span>
 </div>
 </div>
 </div>
 <div class="bg-graylight-5 product-tile-paypal">
 <img class="lazy disp-inline" data-src="https://thegoodguys.sirv.com/Content/BuyNowPayLater/PayPal.svg"/>
 <span class="text-size-90">4 payments of <span class="text-bold">$249.25</span></span>
 </div>
 <!-- END PriceDisplay.jspf --><!--  </div>	 -->
 </div>
 </div>
 <footer class="product-tile-footer">
 <aside class="compare-toggle">
 <div class="compare-toggle-inner clearfix">
 <div class="compare_target compare-toggle-label clearfix" id="compare_3074457345621802168">
 <input id="comparebox_3074457345621802168" name="comparebox_3074457345621802168" onchange="javascript:shoppingActionsJS.addOrRemoveFromCompare('3074457345621802168',this)" onclick="if(this.checked == true){dataLayer.push({'event': 'TGGPD-Req7','TGGPCEventCategory':'Product Compare','TGGPCEventAction':'Add to Compare','TGGPCEventLabel':'50082809'});}" type="checkbox" value="3074457345621802168"/>
 <label for="comparebox_3074457345621802168">Compare</label>
 <a aria-label="Compare" class="compare-toggle-link bg-info-sat" href="javascript:shoppingActionsJS.compareProducts({top_category: '', parent_category_rn: '', categoryId: '11503'});" id="compareButton_3074457345621802168" role="button">Compare</a>
 </div>
 </div>
 </aside>
 <div class="reviews-stars-link" style="margin-left:auto">
 <a class="reviews-stars-link" href="https://www.thegoodguys.com.au/dyson-gen5detect-absolute-cordless-vacuum-443066-01#product_rating_box" onclick="javascript:shoppingActionsJS._rtg_rvws_datalayer('TGGRatingsReviews', 'Ratings &amp; Reviews', 'Read Reviews - Listing', '50082809');">
 <div class="reviews-stars-link__stars reviews-stars text-size-115">
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star-half-o"></i>
 </div>
 <span class="reviews-stars-link__text-link text-medium marg-left-5">(412)</span></a>
 </div>
 </footer>
 </div>
 </div>,
 <div class="product-tile-main clearfix">
 <a aria-hidden="true" class="disp-block" href="https://www.thegoodguys.com.au/dyson-v10-cordless-vacuum-447954-01" id="WC_CatalogEntryDBThumbnailDisplayJSPF_3074457345622166168_link_9b" onclick=" GTMTaggingJS.onNewProductClick('50085577','V10 Cordless Vacuum','799.0','Dyson','Vacuums &amp; Cleaners','BrandCategory','','N/A','DEAL DAYS');
 	" tabindex="-1" title="Dyson V10 Cordless Vacuum">
 <h4 class="product-tile-name">Dyson V10 Cordless Vacuum</h4>
 </a>
 <div class="product-tile-info text-size-90">
 <span class="product-tile-model text-graydark text-nowrap">447954-01</span>
 <span class="text-black text-right text-nowrap"></span>
 </div>
 <div class="product-tile-details">
 <div>
 <div class="product-tile__price" id="product_price_3074457345622166168">
 <!-- 				 <div class="col-xs-7 padd-0 pricepoint product_price_dollar"> -->
 <!-- BEGIN PriceDisplay.jspf --><!-- --><!--  promoPriceAttrValID - 8541059    --><!--  promoCampaignName:: DEAL DAYS --><!--  JSON VALUE :: {"amount":"","Campaign":"DEAL DAYS","endDate":"20-SEP-23","startDate":"07-SEP-23"} --><!--  If leverage price rule to get the price, get the contract unit price. --><!-- grid -->
 <div class="product-tile__price-label pricepoint-promolabel-wrap">
 <div class="pricepoint product_price_dollar">
 <div class="pricepoint clearfix padd-right-5">
 <span class="pricepoint-price" id="offerPrice_3074457345622166168">
 <div class="pricepoint-price--promo"><i class="curr">$</i>799</div>
 </span>
 </div>
 <input id="ProductInfoPrice_3074457345622166168" type="hidden" value="$799.00"/>
 </div>
 <div class="pricepoint-promolabel-wrap__label">
 <div class="promo-label-wrap">
 <span class="promo-label-ribbon bg-dealdays">DEAL DAYS</span>
 </div>
 </div>
 </div>
 <div class="bg-graylight-5 product-tile-paypal">
 <img class="lazy disp-inline" data-src="https://thegoodguys.sirv.com/Content/BuyNowPayLater/PayPal.svg"/>
 <span class="text-size-90">4 payments of <span class="text-bold">$199.75</span></span>
 </div>
 <!-- END PriceDisplay.jspf --><!--  </div>	 -->
 </div>
 </div>
 <footer class="product-tile-footer">
 <aside class="compare-toggle">
 <div class="compare-toggle-inner clearfix">
 <div class="compare_target compare-toggle-label clearfix" id="compare_3074457345622166168">
 <input id="comparebox_3074457345622166168" name="comparebox_3074457345622166168" onchange="javascript:shoppingActionsJS.addOrRemoveFromCompare('3074457345622166168',this)" onclick="if(this.checked == true){dataLayer.push({'event': 'TGGPD-Req7','TGGPCEventCategory':'Product Compare','TGGPCEventAction':'Add to Compare','TGGPCEventLabel':'50085577'});}" type="checkbox" value="3074457345622166168"/>
 <label for="comparebox_3074457345622166168">Compare</label>
 <a aria-label="Compare" class="compare-toggle-link bg-info-sat" href="javascript:shoppingActionsJS.compareProducts({top_category: '', parent_category_rn: '', categoryId: '11503'});" id="compareButton_3074457345622166168" role="button">Compare</a>
 </div>
 </div>
 </aside>
 <div class="reviews-stars-link" style="margin-left:auto">
 <a class="reviews-stars-link" href="https://www.thegoodguys.com.au/dyson-v10-cordless-vacuum-447954-01#product_rating_box" onclick="javascript:shoppingActionsJS._rtg_rvws_datalayer('TGGRatingsReviews', 'Ratings &amp; Reviews', 'Read Reviews - Listing', '50085577');">
 <div class="reviews-stars-link__stars reviews-stars text-size-115">
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star"></i>
 <i aria-hidden="true" class="ggdsicon-star-half-o"></i>
 </div>
 <span class="reviews-stars-link__text-link text-medium marg-left-5">(19)</span></a>
 </div>
 </footer>
 </div>
 </div>,
 <div class="product-tile-main clearfix">
 <a aria-hidden="true" class="disp-block" href="https://www.thegoodguys.com.au/dyson-v15-detect-absolute-cordless-vacuum-447955-01" id="WC_CatalogEntryDBThumbnailDisplayJSPF_3074457345622169168_link_9b" onclick=" GTMTaggingJS.onNewProductClick('50085571','V15 Detect Absolute Cordless Vacuum','1449.0','Dyson','Vacuums &amp; Cleaners','BrandCategory','','N/A','N/A');
 	" tabindex="-1" title="Dyson V15 Detect Absolute Cordless Vacuum">
 <h4 class="product-tile-name">Dyson V15 Detect Absolute Cordless Vacuum</h4>
 </a>
 <div class="product-tile-info text-size-90">
 <span class="product-tile-model text-graydark text-nowrap">447955-01</span>
 <span class="text-black text-right text-nowrap"></span>
 </div>

In [9]:
model_no_list = []
for product in tag_object_model:
    model = product.find('span',{'class':'product-tile-model text-graydark text-nowrap'})
    model_no = model.get_text('', strip = True)
    model_no_list.append(model_no)
model_no_list

['419652-01',
 '394437-01',
 '419671-01',
 '443066-01',
 '447954-01',
 '447955-01',
 '447633-01',
 '447650-01',
 '447949-01',
 '448802-01',
 '419672-01',
 '346614-01',
 '347784-01',
 '369398-01',
 '368678-01',
 '368687-01',
 '394440-01',
 '394438-01',
 '447177-01',
 '447178-01',
 '281999-01',
 '300282-01',
 '300280-01',
 '300272-01',
 '300278-01',
 '281282-01',
 '304640-01',
 '921000-01',
 '969275-01',
 '971434-01',
 '971434-02',
 '971432-01',
 '971447-04',
 '972203-01',
 '972204-01',
 '972214-03',
 '968335-01',
 '971445-01',
 '919648-02',
 '920018-05',
 '967763-02']

In [10]:
#https://stackoverflow.com/questions/14264102/python-beautifulsoup-typeerror-sequence-item-0-expected-string-tag-found
#https://docs.python.org/3/tutorial/errors.html#handling-exceptions

model_price_list = []
for product in tag_object_model:
    try:
        price = product.find('span',{'class':'pricepoint-price'})
        RRP = price.get_text('', strip = True)
    except:
        RRP = '0'
    model_price_list.append(RRP)   
model_price_list

['$1197',
 '$499',
 '$399',
 '$997',
 '$799',
 '$1449',
 '$1349',
 '$1649',
 '$449',
 '$1549',
 '$399',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '$599',
 '$1049',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '$2299',
 '$89',
 '$89',
 '$49',
 '$49',
 '$28',
 '$199',
 '$99',
 '$79',
 '$149',
 '$64',
 '$94',
 '0',
 '0',
 '0']

In [11]:
len(model_no_list)

41

In [12]:
len(model_price_list)

41

In [13]:
df = pd.DataFrame(model_no_list, columns = ['Material_No'])
df

   Material_No
0    419652-01
1    394437-01
2    419671-01
3    443066-01
4    447954-01
5    447955-01
6    447633-01
7    447650-01
8    447949-01
9    448802-01
10   419672-01
11   346614-01
12   347784-01
13   369398-01
14   368678-01
15   368687-01
16   394440-01
17   394438-01
18   447177-01
19   447178-01
20   281999-01
21   300282-01
22   300280-01
23   300272-01
24   300278-01
25   281282-01
26   304640-01
27   921000-01
28   969275-01
29   971434-01
30   971434-02
31   971432-01
32   971447-04
33   972203-01
34   972204-01
35   972214-03
36   968335-01
37   971445-01
38   919648-02
39   920018-05
40   967763-02

In [16]:
df['RRP'] = pd.Series(model_price_list)
df['Date'] = date.today()
df

   Material_No    RRP        Date
0    419652-01  $1197  2023-09-10
1    394437-01   $499  2023-09-10
2    419671-01   $399  2023-09-10
3    443066-01   $997  2023-09-10
4    447954-01   $799  2023-09-10
5    447955-01  $1449  2023-09-10
6    447633-01  $1349  2023-09-10
7    447650-01  $1649  2023-09-10
8    447949-01   $449  2023-09-10
9    448802-01  $1549  2023-09-10
10   419672-01   $399  2023-09-10
11   346614-01      0  2023-09-10
12   347784-01      0  2023-09-10
13   369398-01      0  2023-09-10
14   368678-01      0  2023-09-10
15   368687-01      0  2023-09-10
16   394440-01      0  2023-09-10
17   394438-01      0  2023-09-10
18   447177-01   $599  2023-09-10
19   447178-01  $1049  2023-09-10
20   281999-01      0  2023-09-10
21   300282-01      0  2023-09-10
22   300280-01      0  2023-09-10
23   300272-01      0  2023-09-10
24   300278-01      0  2023-09-10
25   281282-01      0  2023-09-10
26   304640-01  $2299  2023-09-10
27   921000-01    $89  2023-09-10
28   969275-01    $89  2023-09-10
29   971434-01    $49  2023-09-10
30   971434-02    $49  2023-09-10
31   971432-01    $28  2023-09-10
32   971447-04   $199  2023-09-10
33   972203-01    $99  2023-09-10
34   972204-01    $79  2023-09-10
35   972214-03   $149  2023-09-10
36   968335-01    $64  2023-09-10
37   971445-01    $94  2023-09-10
38   919648-02      0  2023-09-10
39   920018-05      0  2023-09-10
40   967763-02      0  2023-09-10