In [1]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page

In [2]:
# import sys
# sys.path.append("VAX GG")

In [3]:
import numpy as np
import pandas as pd

In [4]:
with open('Vax - Vacuums & Cleaners - The Good Guys.html', 'r') as f:
    html_string = f.read()
html_string

'<!DOCTYPE html>\n<!-- saved from url=(0252)https://www.thegoodguys.com.au/vax/vacuums-and-cleaners#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&minHeight:undefined&maxHeight:undefined&minWidth:undefined&maxWidth:undefined&minDepth:undefined&maxDepth:undefined&pageSize:& -->\n<html xmlns:wairole="http://www.w3.org/2005/01/wai-rdf/GUIRoleTaxonomy#" xmlns:waistate="http://www.w3.org/2005/07/aaa" lang="en" xml:lang="en" class="ggds dj_webkit dj_chrome dj_contentbox"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n\t\t\t\t\n\t\t\t<title>\n\t\t\t\tVax - Vacuums &amp; Cleaners - The Good Guys\n\t\t\t</title>\n\t\t\t<meta name="description" content="Shop Vax Vacuums &amp; Cleaners online. The Good Guys stock all the best Vax Vacuums &amp; Cleaners products at the most competitive prices.">\n\t\t\t<meta name="keywords" content="">\n\t\t\t<meta name="pageName" content="SearchResultsPage">\n\t\t\t\n\t\t    <link rel="canonical" href="https://www.thegoodguys.com.au/vax/vacuums-and-cleaners">\n\t\t    \n\t\t\t    \t<link rel="next" href="https://www.thegoodguys.com.au/vax/vacuums-and-cleaners">\n\t\t\t    <!-- Include script files --><!-- BEGIN CommonJSToInclude.jspf -->\n\n<iframe src="javascript:void(0)" title="" role="presentation" style="width: 0px; height: 0px; border: 0px; display: none;" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/saved_resource.html"></iframe><script type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/main.MTAwYzY4Y2VmMA.js.download" data-id="CERN033C77UA35R5E700"></script><script type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/analytics.js.download"></script><script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/main.04e94784.js.download"></script><script gtm="GTM-2DP2" type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/optimize.js.download"></script><script type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/events.js.download"></script><script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/tfa.js.download" id="tb_tfa_script"></script><script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/fbevents.js.download"></script><script type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/pixel.js.download"></script><script type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/kds-events-gtm.min.js.download"></script><script type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/core.js.download"></script><script type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/js"></script><script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/gtm.js.download"></script><script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/intersection-observer.min.js.download"></script>\n<script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/lazyload.min.js.download"></script>\n\n<!--[if IE]> -->\n<script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/object-assign-auto.min.js.download"></script>\n<!-- [endif]-->\n<link rel="preconnect" href="https://thegoodguys.sirv.com/" crossorigin="">\n<link rel="preconnect" href="https://www.google.com/">\n<link rel="preconnect" href="https://www.google.com.au/">\n<link rel="preconnect" href="https://googleads.g.doubleclick.net/">\n<link rel="preconnect" href="https://www.googletagmanager.com/">\n<link rel="preconnect" href="https://stats.g.doubleclick.net/">\n\n<link rel="dns-prefetch" href="https://thegoodguys.sirv.com/">\n\n\n\t<script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/paypal-checkout.min.js.download"></script>\n\t<script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/client.min.js.download"></script>\n\t<script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/data-collector.min.js.download"></script>\n\n\t\t<script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/js(1)" data-uid-auto="uid_zhgiqifdbnmqwwsisqpnlrprksvfvd"></script><script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/pptm.js.download" id="xo-pptm" async=""></script>\n\t\t\n<script type="text/javascript" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/BTPayPal.js.download"></script>\n\n\n\n\n\n<script type="text/javascript" charset="UTF-8" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/dojo.js.download" djconfig="parseOnLoad: true, isDebug: false,  modulePaths: {storetext: &#39;/wcsstore/AUOnlineSAS&#39;}, useCommentedJson: true,locale: &#39;en-us&#39; "></script>\n<script type="text/javascript" charset="UTF-8" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/dojodesktop-rwd.js.download" djconfig="parseOnLoad: true, isDebug: false,  modulePaths: {storetext: &#39;/wcsstore/AUOnlineSAS&#39;}, useCommentedJson: true,locale: &#39;en-us&#39; "></script>\n\n\n<meta name="CommerceSearch" content="storeId_900">\n<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">\n<link rel="shortcut icon" type="image/x-icon" href="https://thegoodguys.sirv.com/icons/favicon.ico?profile=bce">\n<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="https://thegoodguys.sirv.com/icons/apple-touch-icon.png?profile=bce">\n<link rel="apple-touch-icon" type="image/png" sizes="152x152" href="https://thegoodguys.sirv.com/icons/favicon-152x152.png?profile=bce">\n<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="https://thegoodguys.sirv.com/icons/favicon-120x120.png?profile=bce">\n<link rel="icon" type="image/png" sizes="32x32" href="https://thegoodguys.sirv.com/icons/favicon-32x32.png?profile=bce">\n<link rel="icon" type="image/png" sizes="194x194" href="https://thegoodguys.sirv.com/icons/favicon-194x194.png?profile=bce">\n<link rel="icon" type="image/png" sizes="192x192" href="https://thegoodguys.sirv.com/icons/android-chrome-192x192.png?profile=bce">\n<link rel="icon" type="image/png" sizes="16x16" href="https://thegoodguys.sirv.com/icons/favicon-16x16.png?profile=bce">\n<link rel="manifest" href="https://thegoodguys.sirv.com/icons/site.webmanifest">\n<link rel="mask-icon" href="https://thegoodguys.sirv.com/icons/safari-pinned-tab.svg?profile=bce" color="#5bbad5">\n<meta name="msapplication-TileColor" content="#da532c">\n<meta name="msapplication-TileImage" content="//thegoodguys.sirv.com/icons/mstile-144x144.png?profile=bce">\n<meta name="theme-color" content="#ffffff">\n\n<script type="text/javascript">\n//Redirect to HTTPS request in the browser when detect that using HTTP request,\n//since HTTP request is no longer supported in v9.\nvar httpsProtocol = "https:";\nvar securedPort = \'\';\nif (window.location.protocol != httpsProtocol){\n\tvar href = httpsProtocol + window.location.href.substring(window.location.protocol.length);\n\tvar host = window.location.host;\n\tvar hostname = window.location.hostname;\n\tvar httpsHost = httpsHost = (securedPort != "" && securedPort != null) ? hostname + ":" + securedPort : hostname;\n\thref = href.replace(host, httpsHost);\n\twindow.location.href = href;\n}\n</script>\n\n \n\t\t<script type="text/javascript">\n\t\t\tvar WCParamJS={storeId:\'900\',catalogId:\'30000\',langId:\'-1\',pageView:\'\',orderBy:\'\',orderByContent:\'\',searchTerm:\'\',productId:\'\',uniqueId:\'\',productInventoryFlag:\'\',partNumber:\'\'},absoluteURL="https://www.thegoodguys.com.au/",imageDirectoryPath="/wcsstore/AUOnlineSAS/",styleDirectoryPath="images/colors/color1/",supportPaymentTypePromotions="false",subsFulfillmentFrequencyAttrName="fulfillmentFrequency",subsPaymentFrequencyAttrName="paymentFrequency",subsTimePeriodAttrName="timePeriod",storeNLS=null,storeUserType="G",ios=\'false\',android=false,multiSessionEnabled=false,inactivityTimeout=1800000,inactivityWarningDialogDisplayTimer=20000,inactivityWarningDialogBuffer=30000,inactivityTimeoutTracker=null,dialogTimeoutTracker=null;function getAbsoluteURL(){if(""!=absoluteURL){var e=document.URL,t="";-1!=e.indexOf("://")&&(t=e.substring(0,e.indexOf("://")));var a="";-1!=absoluteURL.indexOf("://")&&(a=absoluteURL.substring(0,absoluteURL.indexOf("://"))),t!=a&&(absoluteURL=t+absoluteURL.substring(absoluteURL.indexOf("://")))}return absoluteURL}function getImageDirectoryPath(){return imageDirectoryPath}function getStyleDirectoryPath(){return styleDirectoryPath}\n\t\t</script>\n\t\n\t\t\t\t<script type="text/javascript" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/tggscripts_hm_cat.min.js.download"></script>\n\t\t\t\n<script type="text/javascript" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/Search.js.download"></script>\n<script type="text/javascript" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/search_solr_autosuggest.js.download"></script>\n<script type="text/javascript" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/MiniShopCartDisplay.js.download"></script>\n<script>\n\tdojo.require("wc.service.common");\n\tdojo.require("dojo.number");\n\tdojo.require("dojo.has");\n</script>\n\n\t\t<script type="text/javascript">\n\t\t\tnull==storeNLS&&(dojo.requireLocalization("storetext","StoreText"),storeNLS=dojo.i18n.getLocalization("storetext","StoreText")),initializeInactivityWarning();var ie6=!1,ie7=!1,ie8=!1;null!=navigator&&null!=navigator.userAgent&&(ie6=navigator.userAgent.toLowerCase().indexOf("msie 6.0")>-1,ie7=navigator.userAgent.toLowerCase().indexOf("msie 7.0")>-1,ie8=navigator.userAgent.toLowerCase().indexOf("msie 8.0")>-1),-1==location.href.indexOf("UnsupportedBrowserErrorView")&&(ie6||ie7||ie8)&&document.write(\'<meta http-equiv="Refresh" content="0;URL=https://www.thegoodguys.com.au/UnsupportedBrowserErrorView?catalogId=20000&amp;storeId=900&amp;langId=-1"/>\'),$(document).ready(function(){shoppingActionsJS.setCommonParameters(\'-1\',\'900\',\'30000\',\'G\',\'$\'),shoppingActionsServicesDeclarationJS.setCommonParameters(\'-1\',\'900\',\'30000\');var e=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor),o=/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor);if(e||o)for(var t=dojo.query(\'input[type="hidden"]\'),r=0;r<t.length;r++)t[r].autocomplete="off";(dojo.has("ios")||dojo.has("android"))&&dojo.attr(dojo.body(),"data-wc-device","mobile"),shoppingActionsJS._num_holidays_2_consider=4,shoppingActionsJS._set_store_check()});\n\t\t</script>\t\n\t\n<script type="text/javascript">\n\t \n</script>\n\n<script wid="3da04b88-d810-ea11-828b-00155da08c22" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/t.js.download" defer=""></script>\n\n<link rel="stylesheet" href="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/xxm5tsp.css">\n<!--Start Pre load font -->\n<link rel="preload" as="font" href="https://use.typekit.net/af/2cd6bf/00000000000000000001008f/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n5&amp;v=3" type="font/woff2" crossorigin="">\n<link rel="preload" as="font" href="https://use.typekit.net/af/309dfe/000000000000000000010091/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n7&amp;v=3" type="font/woff2" crossorigin="">\n<link rel="preload" as="font" href="https://use.typekit.net/af/9b05f3/000000000000000000013365/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n4&amp;v=3" type="font/woff2" crossorigin="">\n<link rel="preload" as="font" href="https://use.typekit.net/af/ae4f6c/000000000000000000010096/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n3&amp;v=3" type="font/woff2" crossorigin="">\n<link rel="preload" as="font" href="https://use.typekit.net/af/0c71d1/000000000000000000010097/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n8&amp;v=3" type="font/woff2" crossorigin="">\n<link rel="preload" as="font" href="https://thegoodguys.sirv.com/Content/font/compactash-woff.woff?profile=bce" type="font/woff" crossorigin="">\n<link rel="preload" as="font" href="https://thegoodguys.sirv.com/Content/font/ggds-iconfont-ttf-update-2019-jun.ttf?profile=bce" type="font/ttf" crossorigin="">\n<!-- End Pre load font -->\n\t<link rel="stylesheet" href="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/global.ggds.css">\n\t\n\t\t\t<link rel="stylesheet" href="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/category-brand.ggds.css">\n\t\t<!--Begin EMarketingSpot.jsp --><!-- BEGIN ContentRecommendation.jsp --><!-- JSPs References: HomePage.jsp, BundleDisplay.jsp , CategoryNavigationDisplay.jsp, CompareProductsDisplay.jsp\n\t\t\t\t\t  DynamicKitDisplay.jsp, PackageDisplay.jsp, ProductDisplay.jsp, \n\t\t\t\t\t  SearchResultDisplay.jsp, SubCategoryPage.jsp, TopCategoryPage.jsp\n\t\t\t\t\t   , Footer.jsp , OrderCancelNotify.jsp , OrderCreateNotify.jsp\n\t\t\t\t\t  OrderShipmentNotify.jsp, AccountActivationNotify.jsp, PasswordChangeNotify.jsp,\n\t\t\t\t\t  PasswordResetNotify.jsp, WishlistCreateNotify.jsp,  LandingPage.jsp, \t\n\t\t\t\t\t  ShippingDetailDisplay.jsp, ShopCartDisplay.jsp, StaticContent, \n\t\t\t\t\t  Static JSPs, Footer_UI.jsp, Header_UI.jsp, ProductDescription_UI.jsp  \n\t\t\t\t\t  UserTime--><!-- END ContentRecommendation.jsp --><!-- BEGIN CategoryRecommendation.jsp --><!-- END CategoryRecommendation.jsp --><!-- BEGIN CatalogEntryRecommendation.jsp -->\n\t\t<script type="text/javascript">\n\t\t\twc.render.declareRefreshController({id:"prodRecommendationRefresh_controller_POC_CommonStaticContentEspot",renderContext:wc.render.getContextById("searchBasedNavigation_context"),url:"",formId:"",renderContextChangedHandler:function(e,r){var o=this.renderContext,t=o.properties.resultType;"products"!=t&&"both"!=t||(r.refresh(o.properties),console.log("espot refreshing"))},postRefreshHandler:function(e){this.renderContext;cursor_clear();var r=this.url,o="",t=r.indexOf("emsName=",0);if(t>=0&&(o=r.substring(t+8)).indexOf("&")>=0&&(o="script_"+(o=o.substring(0,o.indexOf("&")))),""!=o&&null!=dojo.byId(o)){var n=dojo.query(".genericESpot",dojo.byId(o).parentNode)[0];null!=n&&dojo.addClass(n,"emptyESpot")}dojo.publish("CMPageRefreshEvent")}});\n\t\t</script>\n\t<!-- END CatalogEntryRecommendation.jsp --><!--End EMarketingSpot.jsp --><!-- END CommonJSToInclude.jspf -->\n\t\t\t<script type="text/javascript" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/SearchBasedNavigationDisplay.js.download"></script>\n\t\t\t<!-- BEGIN CommonGTMScriptToIncludeExt.jspf --><!-- Google Tag Manager -->\n\t<script>\n\t\tdataLayer=[{pageTitle:\'BrandCategory\',visitorLoginState:\'G\'}];\n\t</script>\n\n<script>\n   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\': new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);})(window,document,\'script\',\'dataLayer\',\'GTM-2DP2\');\n</script>\n<!-- END CommonGTMScriptToIncludeExt.jspf --> \n\t\n<script>(window.BOOMR_mq=window.BOOMR_mq||[]).push(["addVar",{"rua.upush":"false","rua.cpush":"false","rua.upre":"false","rua.cpre":"true","rua.uprl":"false","rua.cprl":"false","rua.cprf":"false","rua.trans":"SJ-28dc8271-2bf2-4199-bcda-25708b09746b","rua.cook":"true","rua.ims":"false","rua.ufprl":"false","rua.cfprl":"true","rua.isuxp":"false","rua.texp":"norulematch"}]);</script>\n                              <script>!function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if("False"=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="FDG2S-ZF4G5-GC36U-WAE4Z-YFXRD",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,_,o,r=document.createElement("iframe");if(a[t])a[t]("load",n,!1);else if(a.attachEvent)a.attachEvent("onload",n);r.src="javascript:void(0)",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="width:0;height:0;border:0;display:none;",o=document.getElementsByTagName("script")[0],o.parentNode.insertBefore(r,o);try{_=r.contentWindow.document}catch(O){i=document.domain,r.src="javascript:var d=document.open();d.domain=\'"+i+"\';void(0);",_=r.contentWindow.document}_.open()._l=function(){var a=this.createElement("script");if(i)this.domain=i;a.id="boomr-if-as",a.src=e+"FDG2S-ZF4G5-GC36U-WAE4Z-YFXRD",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},_.write("<bo"+\'dy onload="document._l();">\'),_.close()}}(),"".length>0)if(a&&"performance"in a&&a.performance&&"function"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e="true"=="true"?1:0,t="cookiepresent",n="oztfl7qxy5cmczgyt3rq-f-d4bc65a57-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,_={"ak.v":"36","ak.cp":"702210","ak.ai":parseInt("459134",10),"ak.ol":"0","ak.cr":23,"ak.ipv":4,"ak.proto":"h2","ak.rid":"2f3bb25","ak.r":37441,"ak.a2":e,"ak.m":"a","ak.n":"essl","ak.bpcip":"118.102.85.0","ak.cport":3991,"ak.gh":"23.199.68.189","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"","ak.t":"1691918051","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==YalRI0OC4Jl0fDCVWexr5ZCOuCljPgCzIJBOokekEw0bbJcSZus5CoMFKTUGWgrwAFLfjF7C3i129oJFM/nzxH3lVdAvTEo/A1iHaLeycGUohL5LR7aIHfCzWQxggIz4zeJu5toXJQ2xOOfo3ijq5FVq3i9Ue4qa/dqb51wMAhy8Ikm67oLpHzHy8X6yAMSdQv2O9fgFmojNXZC5GHWUHAFmzBqAAqW7zWdcyxUwvsIKgPEG7+Rvb5BULOYy0pq9ilgocUV444x5J6pSCUNyMBdSPFKGaX4O7ltYUATAAopcSTwTmHHKR5U074ivpvjV559rnBRqMJjnPvq+MGlyUP1/Fuzjs+0Y/QnHmrpkM5EqEh1hctxVTFwCh1UE5RhGuvHDcBJT8c5JNGRuEJmf6gQ412k//PY5+dRcyFPqRFw=","ak.pv":"29","ak.dpoabenc":"","ak.tf":i};if(""!==t)_["ak.ruds"]=t;var o={i:!1,av:function(e){var t="http.initiator";if(e&&(!e[t]||"spa_hard"===e[t]))_["ak.feo"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(_)},rv:function(){var a=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:_,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a("before_beacon",o.av,null,null),a("onbeacon",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);</script><script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/main.642b162b.js.download" async=""></script><script type="text/javascript" async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/muse.js.download"></script><script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/popupJs-09-01-23.min.js.download" async=""></script><script charset="utf-8" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/identify_2ff01.js.download"></script><style type="text/css">button.btn[data-v-f3fb3dc8]{display:inline-block;font-weight:300;line-height:1.25;text-align:center;white-space:nowrap;vertical-align:middle;user-select:none;border:1px solid transparent;cursor:pointer;letter-spacing:1px;transition:all 0.15s ease}button.btn.btn-sm[data-v-f3fb3dc8]{padding:0.4rem 0.8rem;font-size:0.8rem;border-radius:0.2rem}button.btn.btn-primary[data-v-f3fb3dc8]{color:#fff;background-color:#45c8f1;border-color:#45c8f1}button.btn.btn-outline-primary[data-v-f3fb3dc8]{color:#45c8f1;background-color:transparent;border-color:#45c8f1}button.btn.btn-danger[data-v-f3fb3dc8]{color:#fff;background-color:#ff4949;border-color:#ff4949}.text-muted[data-v-f3fb3dc8]{color:#8492a6}.text-center[data-v-f3fb3dc8]{text-align:center}.drop-down-enter[data-v-f3fb3dc8],.drop-down-lea

In [5]:
soup = BeautifulSoup(html_string)

In [6]:
print(soup.prettify())

<!DOCTYPE html>
<!-- saved from url=(0252)https://www.thegoodguys.com.au/vax/vacuums-and-cleaners#facet:&productBeginIndex:0&orderBy:&pageView:grid&minPrice:&maxPrice:&minHeight:undefined&maxHeight:undefined&minWidth:undefined&maxWidth:undefined&minDepth:undefined&maxDepth:undefined&pageSize:& -->
<html class="ggds dj_webkit dj_chrome dj_contentbox" lang="en" xml:lang="en" xmlns:wairole="http://www.w3.org/2005/01/wai-rdf/GUIRoleTaxonomy#" xmlns:waistate="http://www.w3.org/2005/07/aaa">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   Vax - Vacuums &amp; Cleaners - The Good Guys
  </title>
  <meta content="Shop Vax Vacuums &amp; Cleaners online. The Good Guys stock all the best Vax Vacuums &amp; Cleaners products at the most competitive prices." name="description"/>
  <meta content="" name="keywords"/>
  <meta content="SearchResultsPage" name="pageName"/>
  <link href="https://www.thegoodguys.com.au/vax/vacuums-and-cleaners" rel="canonical"/>
  <link href="https://www.thegoodguys.com.au/vax/vacuums-and-cleaners" rel="next"/>
  <!-- Include script files -->
  <!-- BEGIN CommonJSToInclude.jspf -->
 </head>
 <body>
  <iframe role="presentation" src="javascript:void(0)" style="width: 0px; height: 0px; border: 0px; display: none;" title="">
  </iframe>
  <script async="" data-id="CERN033C77UA35R5E700" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/main.MTAwYzY4Y2VmMA.js.download" type="text/javascript">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/analytics.js.download" type="text/javascript">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/main.04e94784.js.download">
  </script>
  <script async="" gtm="GTM-2DP2" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/optimize.js.download" type="text/javascript">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/events.js.download" type="text/javascript">
  </script>
  <script async="" id="tb_tfa_script" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/tfa.js.download">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/fbevents.js.download">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/pixel.js.download" type="text/javascript">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/kds-events-gtm.min.js.download" type="text/javascript">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/core.js.download" type="text/javascript">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/js" type="text/javascript">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/gtm.js.download">
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/intersection-observer.min.js.download">
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/lazyload.min.js.download">
  </script>
  <!--[if IE]> -->
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/object-assign-auto.min.js.download">
  </script>
  <!-- [endif]-->
  <link crossorigin="" href="https://thegoodguys.sirv.com/" rel="preconnect"/>
  <link href="https://www.google.com/" rel="preconnect"/>
  <link href="https://www.google.com.au/" rel="preconnect"/>
  <link href="https://googleads.g.doubleclick.net/" rel="preconnect"/>
  <link href="https://www.googletagmanager.com/" rel="preconnect"/>
  <link href="https://stats.g.doubleclick.net/" rel="preconnect"/>
  <link href="https://thegoodguys.sirv.com/" rel="dns-prefetch"/>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/paypal-checkout.min.js.download">
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/client.min.js.download">
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/data-collector.min.js.download">
  </script>
  <script data-uid-auto="uid_zhgiqifdbnmqwwsisqpnlrprksvfvd" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/js(1)">
  </script>
  <script async="" id="xo-pptm" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/pptm.js.download">
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/BTPayPal.js.download" type="text/javascript">
  </script>
  <script charset="UTF-8" djconfig="parseOnLoad: true, isDebug: false,  modulePaths: {storetext: '/wcsstore/AUOnlineSAS'}, useCommentedJson: true,locale: 'en-us' " src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/dojo.js.download" type="text/javascript">
  </script>
  <script charset="UTF-8" djconfig="parseOnLoad: true, isDebug: false,  modulePaths: {storetext: '/wcsstore/AUOnlineSAS'}, useCommentedJson: true,locale: 'en-us' " src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/dojodesktop-rwd.js.download" type="text/javascript">
  </script>
  <meta content="storeId_900" name="CommerceSearch"/>
  <meta content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
  <link href="https://thegoodguys.sirv.com/icons/favicon.ico?profile=bce" rel="shortcut icon" type="image/x-icon"/>
  <link href="https://thegoodguys.sirv.com/icons/apple-touch-icon.png?profile=bce" rel="apple-touch-icon" sizes="180x180" type="image/png"/>
  <link href="https://thegoodguys.sirv.com/icons/favicon-152x152.png?profile=bce" rel="apple-touch-icon" sizes="152x152" type="image/png"/>
  <link href="https://thegoodguys.sirv.com/icons/favicon-120x120.png?profile=bce" rel="apple-touch-icon" sizes="120x120" type="image/png"/>
  <link href="https://thegoodguys.sirv.com/icons/favicon-32x32.png?profile=bce" rel="icon" sizes="32x32" type="image/png"/>
  <link href="https://thegoodguys.sirv.com/icons/favicon-194x194.png?profile=bce" rel="icon" sizes="194x194" type="image/png"/>
  <link href="https://thegoodguys.sirv.com/icons/android-chrome-192x192.png?profile=bce" rel="icon" sizes="192x192" type="image/png"/>
  <link href="https://thegoodguys.sirv.com/icons/favicon-16x16.png?profile=bce" rel="icon" sizes="16x16" type="image/png"/>
  <link href="https://thegoodguys.sirv.com/icons/site.webmanifest" rel="manifest"/>
  <link color="#5bbad5" href="https://thegoodguys.sirv.com/icons/safari-pinned-tab.svg?profile=bce" rel="mask-icon"/>
  <meta content="#da532c" name="msapplication-TileColor"/>
  <meta content="//thegoodguys.sirv.com/icons/mstile-144x144.png?profile=bce" name="msapplication-TileImage"/>
  <meta content="#ffffff" name="theme-color"/>
  <script type="text/javascript">
   //Redirect to HTTPS request in the browser when detect that using HTTP request,
//since HTTP request is no longer supported in v9.
var httpsProtocol = "https:";
var securedPort = '';
if (window.location.protocol != httpsProtocol){
	var href = httpsProtocol + window.location.href.substring(window.location.protocol.length);
	var host = window.location.host;
	var hostname = window.location.hostname;
	var httpsHost = httpsHost = (securedPort != "" && securedPort != null) ? hostname + ":" + securedPort : hostname;
	href = href.replace(host, httpsHost);
	window.location.href = href;
}
  </script>
  <script type="text/javascript">
   var WCParamJS={storeId:'900',catalogId:'30000',langId:'-1',pageView:'',orderBy:'',orderByContent:'',searchTerm:'',productId:'',uniqueId:'',productInventoryFlag:'',partNumber:''},absoluteURL="https://www.thegoodguys.com.au/",imageDirectoryPath="/wcsstore/AUOnlineSAS/",styleDirectoryPath="images/colors/color1/",supportPaymentTypePromotions="false",subsFulfillmentFrequencyAttrName="fulfillmentFrequency",subsPaymentFrequencyAttrName="paymentFrequency",subsTimePeriodAttrName="timePeriod",storeNLS=null,storeUserType="G",ios='false',android=false,multiSessionEnabled=false,inactivityTimeout=1800000,inactivityWarningDialogDisplayTimer=20000,inactivityWarningDialogBuffer=30000,inactivityTimeoutTracker=null,dialogTimeoutTracker=null;function getAbsoluteURL(){if(""!=absoluteURL){var e=document.URL,t="";-1!=e.indexOf("://")&&(t=e.substring(0,e.indexOf("://")));var a="";-1!=absoluteURL.indexOf("://")&&(a=absoluteURL.substring(0,absoluteURL.indexOf("://"))),t!=a&&(absoluteURL=t+absoluteURL.substring(absoluteURL.indexOf("://")))}return absoluteURL}function getImageDirectoryPath(){return imageDirectoryPath}function getStyleDirectoryPath(){return styleDirectoryPath}
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/tggscripts_hm_cat.min.js.download" type="text/javascript">
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/Search.js.download" type="text/javascript">
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/search_solr_autosuggest.js.download" type="text/javascript">
  </script>
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/MiniShopCartDisplay.js.download" type="text/javascript">
  </script>
  <script>
   dojo.require("wc.service.common");
	dojo.require("dojo.number");
	dojo.require("dojo.has");
  </script>
  <script type="text/javascript">
   null==storeNLS&&(dojo.requireLocalization("storetext","StoreText"),storeNLS=dojo.i18n.getLocalization("storetext","StoreText")),initializeInactivityWarning();var ie6=!1,ie7=!1,ie8=!1;null!=navigator&&null!=navigator.userAgent&&(ie6=navigator.userAgent.toLowerCase().indexOf("msie 6.0")>-1,ie7=navigator.userAgent.toLowerCase().indexOf("msie 7.0")>-1,ie8=navigator.userAgent.toLowerCase().indexOf("msie 8.0")>-1),-1==location.href.indexOf("UnsupportedBrowserErrorView")&&(ie6||ie7||ie8)&&document.write('<meta http-equiv="Refresh" content="0;URL=https://www.thegoodguys.com.au/UnsupportedBrowserErrorView?catalogId=20000&amp;storeId=900&amp;langId=-1"/>'),$(document).ready(function(){shoppingActionsJS.setCommonParameters('-1','900','30000','G','$'),shoppingActionsServicesDeclarationJS.setCommonParameters('-1','900','30000');var e=/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor),o=/Safari/.test(navigator.userAgent)&&/Apple Computer/.test(navigator.vendor);if(e||o)for(var t=dojo.query('input[type="hidden"]'),r=0;r<t.length;r++)t[r].autocomplete="off";(dojo.has("ios")||dojo.has("android"))&&dojo.attr(dojo.body(),"data-wc-device","mobile"),shoppingActionsJS._num_holidays_2_consider=4,shoppingActionsJS._set_store_check()});
  </script>
  <script type="text/javascript">
  </script>
  <script defer="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/t.js.download" wid="3da04b88-d810-ea11-828b-00155da08c22">
  </script>
  <link href="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/xxm5tsp.css" rel="stylesheet"/>
  <!--Start Pre load font -->
  <link as="font" crossorigin="" href="https://use.typekit.net/af/2cd6bf/00000000000000000001008f/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n5&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://use.typekit.net/af/309dfe/000000000000000000010091/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n7&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://use.typekit.net/af/9b05f3/000000000000000000013365/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n4&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://use.typekit.net/af/ae4f6c/000000000000000000010096/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n3&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://use.typekit.net/af/0c71d1/000000000000000000010097/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&amp;fvd=n8&amp;v=3" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://thegoodguys.sirv.com/Content/font/compactash-woff.woff?profile=bce" rel="preload" type="font/woff"/>
  <link as="font" crossorigin="" href="https://thegoodguys.sirv.com/Content/font/ggds-iconfont-ttf-update-2019-jun.ttf?profile=bce" rel="preload" type="font/ttf"/>
  <!-- End Pre load font -->
  <link href="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/global.ggds.css" rel="stylesheet"/>
  <link href="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/category-brand.ggds.css" rel="stylesheet"/>
  <!--Begin EMarketingSpot.jsp -->
  <!-- BEGIN ContentRecommendation.jsp -->
  <!-- JSPs References: HomePage.jsp, BundleDisplay.jsp , CategoryNavigationDisplay.jsp, CompareProductsDisplay.jsp
					  DynamicKitDisplay.jsp, PackageDisplay.jsp, ProductDisplay.jsp,
					  SearchResultDisplay.jsp, SubCategoryPage.jsp, TopCategoryPage.jsp
					   , Footer.jsp , OrderCancelNotify.jsp , OrderCreateNotify.jsp
					  OrderShipmentNotify.jsp, AccountActivationNotify.jsp, PasswordChangeNotify.jsp,
					  PasswordResetNotify.jsp, WishlistCreateNotify.jsp,  LandingPage.jsp,
					  ShippingDetailDisplay.jsp, ShopCartDisplay.jsp, StaticContent,
					  Static JSPs, Footer_UI.jsp, Header_UI.jsp, ProductDescription_UI.jsp
					  UserTime-->
  <!-- END ContentRecommendation.jsp -->
  <!-- BEGIN CategoryRecommendation.jsp -->
  <!-- END CategoryRecommendation.jsp -->
  <!-- BEGIN CatalogEntryRecommendation.jsp -->
  <script type="text/javascript">
   wc.render.declareRefreshController({id:"prodRecommendationRefresh_controller_POC_CommonStaticContentEspot",renderContext:wc.render.getContextById("searchBasedNavigation_context"),url:"",formId:"",renderContextChangedHandler:function(e,r){var o=this.renderContext,t=o.properties.resultType;"products"!=t&&"both"!=t||(r.refresh(o.properties),console.log("espot refreshing"))},postRefreshHandler:function(e){this.renderContext;cursor_clear();var r=this.url,o="",t=r.indexOf("emsName=",0);if(t>=0&&(o=r.substring(t+8)).indexOf("&")>=0&&(o="script_"+(o=o.substring(0,o.indexOf("&")))),""!=o&&null!=dojo.byId(o)){var n=dojo.query(".genericESpot",dojo.byId(o).parentNode)[0];null!=n&&dojo.addClass(n,"emptyESpot")}dojo.publish("CMPageRefreshEvent")}});
  </script>
  <!-- END CatalogEntryRecommendation.jsp -->
  <!--End EMarketingSpot.jsp -->
  <!-- END CommonJSToInclude.jspf -->
  <script src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/SearchBasedNavigationDisplay.js.download" type="text/javascript">
  </script>
  <!-- BEGIN CommonGTMScriptToIncludeExt.jspf -->
  <!-- Google Tag Manager -->
  <script>
   dataLayer=[{pageTitle:'BrandCategory',visitorLoginState:'G'}];
  </script>
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-2DP2');
  </script>
  <!-- END CommonGTMScriptToIncludeExt.jspf -->
  <script>
   (window.BOOMR_mq=window.BOOMR_mq||[]).push(["addVar",{"rua.upush":"false","rua.cpush":"false","rua.upre":"false","rua.cpre":"true","rua.uprl":"false","rua.cprl":"false","rua.cprf":"false","rua.trans":"SJ-28dc8271-2bf2-4199-bcda-25708b09746b","rua.cook":"true","rua.ims":"false","rua.ufprl":"false","rua.cfprl":"true","rua.isuxp":"false","rua.texp":"norulematch"}]);
  </script>
  <script>
   !function(a){var e="https://s.go-mpulse.net/boomerang/",t="addEventListener";if("False"=="True")a.BOOMR_config=a.BOOMR_config||{},a.BOOMR_config.PageParams=a.BOOMR_config.PageParams||{},a.BOOMR_config.PageParams.pci=!0,e="https://s2.go-mpulse.net/boomerang/";if(window.BOOMR_API_key="FDG2S-ZF4G5-GC36U-WAE4Z-YFXRD",function(){function n(e){a.BOOMR_onload=e&&e.timeStamp||(new Date).getTime()}if(!a.BOOMR||!a.BOOMR.version&&!a.BOOMR.snippetExecuted){a.BOOMR=a.BOOMR||{},a.BOOMR.snippetExecuted=!0;var i,_,o,r=document.createElement("iframe");if(a[t])a[t]("load",n,!1);else if(a.attachEvent)a.attachEvent("onload",n);r.src="javascript:void(0)",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="width:0;height:0;border:0;display:none;",o=document.getElementsByTagName("script")[0],o.parentNode.insertBefore(r,o);try{_=r.contentWindow.document}catch(O){i=document.domain,r.src="javascript:var d=document.open();d.domain='"+i+"';void(0);",_=r.contentWindow.document}_.open()._l=function(){var a=this.createElement("script");if(i)this.domain=i;a.id="boomr-if-as",a.src=e+"FDG2S-ZF4G5-GC36U-WAE4Z-YFXRD",BOOMR_lstart=(new Date).getTime(),this.body.appendChild(a)},_.write("<bo"+'dy onload="document._l();">'),_.close()}}(),"".length>0)if(a&&"performance"in a&&a.performance&&"function"==typeof a.performance.setResourceTimingBufferSize)a.performance.setResourceTimingBufferSize();!function(){if(BOOMR=a.BOOMR||{},BOOMR.plugins=BOOMR.plugins||{},!BOOMR.plugins.AK){var e="true"=="true"?1:0,t="cookiepresent",n="oztfl7qxy5cmczgyt3rq-f-d4bc65a57-clientnsv4-s.akamaihd.net",i="false"=="true"?2:1,_={"ak.v":"36","ak.cp":"702210","ak.ai":parseInt("459134",10),"ak.ol":"0","ak.cr":23,"ak.ipv":4,"ak.proto":"h2","ak.rid":"2f3bb25","ak.r":37441,"ak.a2":e,"ak.m":"a","ak.n":"essl","ak.bpcip":"118.102.85.0","ak.cport":3991,"ak.gh":"23.199.68.189","ak.quicv":"","ak.tlsv":"tls1.3","ak.0rtt":"","ak.csrc":"-","ak.acc":"","ak.t":"1691918051","ak.ak":"hOBiQwZUYzCg5VSAfCLimQ==YalRI0OC4Jl0fDCVWexr5ZCOuCljPgCzIJBOokekEw0bbJcSZus5CoMFKTUGWgrwAFLfjF7C3i129oJFM/nzxH3lVdAvTEo/A1iHaLeycGUohL5LR7aIHfCzWQxggIz4zeJu5toXJQ2xOOfo3ijq5FVq3i9Ue4qa/dqb51wMAhy8Ikm67oLpHzHy8X6yAMSdQv2O9fgFmojNXZC5GHWUHAFmzBqAAqW7zWdcyxUwvsIKgPEG7+Rvb5BULOYy0pq9ilgocUV444x5J6pSCUNyMBdSPFKGaX4O7ltYUATAAopcSTwTmHHKR5U074ivpvjV559rnBRqMJjnPvq+MGlyUP1/Fuzjs+0Y/QnHmrpkM5EqEh1hctxVTFwCh1UE5RhGuvHDcBJT8c5JNGRuEJmf6gQ412k//PY5+dRcyFPqRFw=","ak.pv":"29","ak.dpoabenc":"","ak.tf":i};if(""!==t)_["ak.ruds"]=t;var o={i:!1,av:function(e){var t="http.initiator";if(e&&(!e[t]||"spa_hard"===e[t]))_["ak.feo"]=void 0!==a.aFeoApplied?1:0,BOOMR.addVar(_)},rv:function(){var a=["ak.bpcip","ak.cport","ak.cr","ak.csrc","ak.gh","ak.ipv","ak.m","ak.n","ak.ol","ak.proto","ak.quicv","ak.tlsv","ak.0rtt","ak.r","ak.acc","ak.t","ak.tf"];BOOMR.removeVar(a)}};BOOMR.plugins.AK={akVars:_,akDNSPreFetchDomain:n,init:function(){if(!o.i){var a=BOOMR.subscribe;a("before_beacon",o.av,null,null),a("onbeacon",o.rv,null,null),o.i=!0}return this},is_complete:function(){return!0}}}}()}(window);
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/main.642b162b.js.download">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/muse.js.download" type="text/javascript">
  </script>
  <script async="" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/popupJs-09-01-23.min.js.download">
  </script>
  <script charset="utf-8" src="./Vax - Vacuums &amp; Cleaners - The Good Guys_files/identify_2ff01.js.download">
  </script>
  <style type="text/css">

In [7]:
tag_object_model=soup.find_all('span',{'class':'product-tile-model text-graydark text-nowrap'})
tag_object_model

[<span class="product-tile-model text-graydark text-nowrap">VX73</span>,
 <span class="product-tile-model text-graydark text-nowrap">VACSC21E</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX74</span>,
 <span class="product-tile-model text-graydark text-nowrap">VFT22A</span>,
 <span class="product-tile-model text-graydark text-nowrap">90600</span>,
 <span class="product-tile-model text-graydark text-nowrap">VSSSF22U</span>,
 <span class="product-tile-model text-graydark text-nowrap">VSSCB22V</span>,
 <span class="product-tile-model text-graydark text-nowrap">VPLCS1L22C2</span>,
 <span class="product-tile-model text-graydark text-nowrap">VCP7PTFLT2</span>,
 <span class="product-tile-model text-graydark text-nowrap">VWV21C</span>,
 <span class="product-tile-model text-graydark text-nowrap">VCP6BFLT</span>,
 <span class="product-tile-model text-graydark text-nowrap">VTHSP4</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX40B</span>,
 <span class="product-tile-model text-graydark text-nowrap">VSPC</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX83</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX22</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX40</span>,
 <span class="product-tile-model text-graydark text-nowrap">VSV21D2</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX24S</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX97</span>,
 <span class="product-tile-model text-graydark text-nowrap">VSV21W</span>,
 <span class="product-tile-model text-graydark text-nowrap">VSV21Y</span>,
 <span class="product-tile-model text-graydark text-nowrap">VXCB-01</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX100</span>,
 <span class="product-tile-model text-graydark text-nowrap">VSPP</span>,
 <span class="product-tile-model text-graydark text-nowrap">VX89</span>]

In [8]:
model_no_list = []
for model in tag_object_model:
    model_No = model.contents
    model_no_list.append(model_No)
model_no_list

[['VX73'],
 ['VACSC21E'],
 ['VX74'],
 ['VFT22A'],
 ['90600'],
 ['VSSSF22U'],
 ['VSSCB22V'],
 ['VPLCS1L22C2'],
 ['VCP7PTFLT2'],
 ['VWV21C'],
 ['VCP6BFLT'],
 ['VTHSP4'],
 ['VX40B'],
 ['VSPC'],
 ['VX83'],
 ['VX22'],
 ['VX40'],
 ['VSV21D2'],
 ['VX24S'],
 ['VX97'],
 ['VSV21W'],
 ['VSV21Y'],
 ['VXCB-01'],
 ['VX100'],
 ['VSPP'],
 ['VX89']]

In [9]:
tag_object_price=soup.find_all('span',{'class':'pricepoint-price'})
tag_object_price

[<span class="pricepoint-price" id="offerPrice_3074457345619049170">
 <div class="pricepoint-price--promo"><i class="curr">$</i>129</div>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621313169">
 <div class="pricepoint-price--promo"><i class="curr">$</i>169</div>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345618931669">
 <div class="pricepoint-price--promo"><i class="curr">$</i>199</div>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621980168">
 <i class="curr">$</i>14
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $3
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_27501">
 <i class="curr">$</i>19
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $6
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621786168">
 <i class="curr">$</i>23
 					</span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621786169">
 <i class="curr">$</i>23
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $6
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621848168">
 <i class="curr">$</i>23
 					</span>,
 <span class="pricepoint-price" id="offerPrice_3074457345619907668">
 <i class="curr">$</i>24
 					</span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621829169">
 <i class="curr">$</i>24
 					</span>,
 <span class="pricepoint-price" id="offerPrice_12310">
 <i class="curr">$</i>26
 					</span>,
 <span class="pricepoint-price" id="offerPrice_548001">
 <i class="curr">$</i>26
 					</span>,
 <span class="pricepoint-price" id="offerPrice_3074457345619909669">
 <i class="curr">$</i>29
 					</span>,
 <span class="pricepoint-price" id="offerPrice_3074457345619909668">
 <i class="curr">$</i>34
 					</span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621486668">
 <i class="curr">$</i>96
 					</span>,
 <span class="pricepoint-price" id="offerPrice_556001">
 <i class="curr">$</i>99
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $24
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621650168">
 <i class="curr">$</i>196
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $7
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345619901169">
 <i class="curr">$</i>199
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $10
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345619901170">
 <i class="curr">$</i>219
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $12
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621466669">
 <i class="curr">$</i>249
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $7
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621466668">
 <i class="curr">$</i>299
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $7
 							</span>
 </span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621486669">
 <i class="curr">$</i>349
 					</span>,
 <span class="pricepoint-price" id="offerPrice_3074457345621313168">
 <i class="curr">$</i>399
 							<span class="pricepoint-minDelvPrice" id="minDelvPrice">
 								+ Delivery from $24
 							</span>
 </span>]

In [10]:
# np.dtype(tag_object_price)

In [11]:
#https://stackoverflow.com/questions/14264102/python-beautifulsoup-typeerror-sequence-item-0-expected-string-tag-found

price_list = []
for price in tag_object_price:
    RRP = price.get_text('', strip = True)
    price_list.append(RRP)
price_list

['$129',
 '$169',
 '$199',
 '$14+ Delivery from $3',
 '$19+ Delivery from $6',
 '$23',
 '$23+ Delivery from $6',
 '$23',
 '$24',
 '$24',
 '$26',
 '$26',
 '$29',
 '$34',
 '$96',
 '$99+ Delivery from $24',
 '$196+ Delivery from $7',
 '$199+ Delivery from $10',
 '$219+ Delivery from $12',
 '$249+ Delivery from $7',
 '$299+ Delivery from $7',
 '$349',
 '$399+ Delivery from $24']

In [12]:
df = pd.DataFrame(model_no_list, columns = ['Material_No'])
df

    Material_No
0          VX73
1      VACSC21E
2          VX74
3        VFT22A
4         90600
5      VSSSF22U
6      VSSCB22V
7   VPLCS1L22C2
8    VCP7PTFLT2
9        VWV21C
10     VCP6BFLT
11       VTHSP4
12        VX40B
13         VSPC
14         VX83
15         VX22
16         VX40
17      VSV21D2
18        VX24S
19         VX97
20       VSV21W
21       VSV21Y
22      VXCB-01
23        VX100
24         VSPP
25         VX89

In [13]:
df['RRP'] = pd.Series(price_list)
df

    Material_No                      RRP
0          VX73                     $129
1      VACSC21E                     $169
2          VX74                     $199
3        VFT22A    $14+ Delivery from $3
4         90600    $19+ Delivery from $6
5      VSSSF22U                      $23
6      VSSCB22V    $23+ Delivery from $6
7   VPLCS1L22C2                      $23
8    VCP7PTFLT2                      $24
9        VWV21C                      $24
10     VCP6BFLT                      $26
11       VTHSP4                      $26
12        VX40B                      $29
13         VSPC                      $34
14         VX83                      $96
15         VX22   $99+ Delivery from $24
16         VX40   $196+ Delivery from $7
17      VSV21D2  $199+ Delivery from $10
18        VX24S  $219+ Delivery from $12
19         VX97   $249+ Delivery from $7
20       VSV21W   $299+ Delivery from $7
21       VSV21Y                     $349
22      VXCB-01  $399+ Delivery from $24
23        VX100                      NaN
24         VSPP                      NaN
25         VX89                      NaN